// AUTO-GENERATED by scripts/generate-app-icons.mjs — do not edit by hand.
export type BrandAssetGroup = "favicon" | "apple" | "maskable" | "splash" | "logo" | "social";

export interface BrandAsset {
  /** Public URL, served from /public. */
  file: string;
  group: BrandAssetGroup;
  /** Where the asset is used. */
  label: string;
  /** Intrinsic pixel size (0 for vector). */
  width: number;
  height: number;
  bytes: number;
}

export const BRAND_ASSETS: BrandAsset[] = [
  {
    "file": "/icons/favicon-16.png",
    "group": "favicon",
    "label": "Favicon (browser tab)",
    "width": 16,
    "height": 16,
    "bytes": 660
  },
  {
    "file": "/icons/favicon-32.png",
    "group": "favicon",
    "label": "Favicon (retina tab)",
    "width": 32,
    "height": 32,
    "bytes": 1233
  },
  {
    "file": "/icons/favicon-48.png",
    "group": "favicon",
    "label": "Favicon (Windows tile)",
    "width": 48,
    "height": 48,
    "bytes": 1820
  },
  {
    "file": "/favicon.png",
    "group": "favicon",
    "label": "Favicon (default)",
    "width": 64,
    "height": 64,
    "bytes": 2404
  },
  {
    "file": "/icons/icon-96.png",
    "group": "favicon",
    "label": "Android launcher (ldpi)",
    "width": 96,
    "height": 96,
    "bytes": 4159
  },
  {
    "file": "/icons/icon-128.png",
    "group": "favicon",
    "label": "Chrome Web Store / desktop",
    "width": 128,
    "height": 128,
    "bytes": 6518
  },
  {
    "file": "/icons/icon-256.png",
    "group": "favicon",
    "label": "Desktop app icon",
    "width": 256,
    "height": 256,
    "bytes": 13500
  },
  {
    "file": "/icons/icon-384.png",
    "group": "favicon",
    "label": "Android launcher (xxhdpi)",
    "width": 384,
    "height": 384,
    "bytes": 17060
  },
  {
    "file": "/icon-192.png",
    "group": "favicon",
    "label": "PWA icon (Android home screen)",
    "width": 192,
    "height": 192,
    "bytes": 8357
  },
  {
    "file": "/icon-512.png",
    "group": "favicon",
    "label": "PWA icon (splash + store listing)",
    "width": 512,
    "height": 512,
    "bytes": 27612
  },
  {
    "file": "/icons/apple-touch-icon-120.png",
    "group": "apple",
    "label": "iPhone home screen (@2x)",
    "width": 120,
    "height": 120,
    "bytes": 4077
  },
  {
    "file": "/icons/apple-touch-icon-152.png",
    "group": "apple",
    "label": "iPad home screen (@2x)",
    "width": 152,
    "height": 152,
    "bytes": 5658
  },
  {
    "file": "/icons/apple-touch-icon-167.png",
    "group": "apple",
    "label": "iPad Pro home screen",
    "width": 167,
    "height": 167,
    "bytes": 6452
  },
  {
    "file": "/apple-touch-icon.png",
    "group": "apple",
    "label": "iPhone home screen (@3x)",
    "width": 180,
    "height": 180,
    "bytes": 5351
  },
  {
    "file": "/icons/maskable-192.png",
    "group": "maskable",
    "label": "Android maskable (adaptive)",
    "width": 192,
    "height": 192,
    "bytes": 5922
  },
  {
    "file": "/icons/maskable-512.png",
    "group": "maskable",
    "label": "Android maskable (large)",
    "width": 512,
    "height": 512,
    "bytes": 13839
  },
  {
    "file": "/splash/splash-1290x2796.png",
    "group": "splash",
    "label": "iPhone 15/16 Pro Max",
    "width": 1290,
    "height": 2796,
    "bytes": 884152
  },
  {
    "file": "/splash/splash-1179x2556.png",
    "group": "splash",
    "label": "iPhone 15/16",
    "width": 1179,
    "height": 2556,
    "bytes": 755401
  },
  {
    "file": "/splash/splash-1170x2532.png",
    "group": "splash",
    "label": "iPhone 12–14",
    "width": 1170,
    "height": 2532,
    "bytes": 742449
  },
  {
    "file": "/splash/splash-1125x2436.png",
    "group": "splash",
    "label": "iPhone X/XS/11 Pro",
    "width": 1125,
    "height": 2436,
    "bytes": 699345
  },
  {
    "file": "/splash/splash-1536x2048.png",
    "group": "splash",
    "label": "iPad 9.7\"",
    "width": 1536,
    "height": 2048,
    "bytes": 749108
  },
  {
    "file": "/splash/splash-1668x2388.png",
    "group": "splash",
    "label": "iPad Pro 11\"",
    "width": 1668,
    "height": 2388,
    "bytes": 927883
  },
  {
    "file": "/splash/splash-2048x2732.png",
    "group": "splash",
    "label": "iPad Pro 12.9\"",
    "width": 2048,
    "height": 2732,
    "bytes": 1250281
  },
  {
    "file": "/gradr-logo.png",
    "group": "logo",
    "label": "Primary symbol (light surfaces)",
    "width": 512,
    "height": 512,
    "bytes": 20649
  },
  {
    "file": "/gradr-logo-dark.png",
    "group": "logo",
    "label": "Primary symbol (dark surfaces)",
    "width": 512,
    "height": 512,
    "bytes": 20330
  },
  {
    "file": "/gradr-logo.svg",
    "group": "logo",
    "label": "Vector symbol (infinite scale)",
    "width": 0,
    "height": 0,
    "bytes": 2399
  },
  {
    "file": "/gradr-logo-mono.svg",
    "group": "logo",
    "label": "Monochrome symbol (currentColor)",
    "width": 0,
    "height": 0,
    "bytes": 2409
  },
  {
    "file": "/gradr-symbol-compact.svg",
    "group": "logo",
    "label": "Small-size symbol (16–64px)",
    "width": 0,
    "height": 0,
    "bytes": 2399
  },
  {
    "file": "/gradr-lockup.png",
    "group": "logo",
    "label": "Symbol + GRADR lockup (light)",
    "width": 1200,
    "height": 320,
    "bytes": 20837
  },
  {
    "file": "/gradr-lockup-dark.png",
    "group": "logo",
    "label": "Symbol + GRADR lockup (dark)",
    "width": 1200,
    "height": 320,
    "bytes": 20285
  },
  {
    "file": "/email-logo-144.png",
    "group": "logo",
    "label": "Email header mark",
    "width": 144,
    "height": 144,
    "bytes": 4893
  },
  {
    "file": "/og.png",
    "group": "social",
    "label": "Open Graph / Twitter card",
    "width": 1200,
    "height": 630,
    "bytes": 66692
  },
  {
    "file": "/og/site-gradr.png",
    "group": "social",
    "label": "Site social card (source)",
    "width": 1200,
    "height": 630,
    "bytes": 152329
  }
];
