/**
 * Bundled v1 of the remaining Gradr policies: Acceptable Use, AI disclosure,
 * Disclaimer & limitation of liability, Affiliate disclosure and the
 * sub-processor register.
 *
 * Same markdown subset as `legalDocs.ts` (`## heading`, `- bullet`, paragraphs,
 * `**bold**`, `[label](href)`). These are static bundled documents.
 *
 * FACTUAL DISCIPLINE: nothing in this file may state a company registration,
 * address, tax number, certification, audit outcome or retention period that
 * has not been supplied by the business owner. Unknown values are rendered
 * from `src/content/companyIdentity.ts`, which prints an obvious
 * "[TO BE PROVIDED]" marker rather than an invented value.
 */
import {
  SELLER_CONTACT_EMAIL,
  SELLER_DOMAIN,
  SELLER_LEGAL_NAME,
  SELLER_WEBSITE_URL,
  REFUND_WINDOW_DAYS,
} from "./legal";
import { LEGAL_CONTACT_EMAIL, PRIVACY_CONTACT_EMAIL } from "./companyIdentity";

export const POLICIES_V1_EFFECTIVE = "2026-08-24";

export const ACCEPTABLE_USE_V1 = `## 1. Who this applies to

This Acceptable Use Policy applies to everyone who uses Gradr at ${SELLER_WEBSITE_URL} and app.${SELLER_DOMAIN}, on any plan, including free and trial accounts. It forms part of the [Terms & Conditions](/terms). Where the two documents overlap, the Terms govern.

## 2. Use Gradr for your own career

Gradr is a personal career workspace. You may use it to work on your own applications, your own resume and your own interview practice. You may not resell access, share one account between people, or operate Gradr on behalf of third parties without a written agreement with us.

## 3. Content standards

You are responsible for everything you upload, generate or send through Gradr. Do not upload or produce content that:

- You have no right to use, including another person's resume, ID documents, or confidential employer material.
- Misrepresents your identity, employment history, education, certifications or right to work.
- Is unlawful, defamatory, harassing, hateful, sexually explicit, or discriminatory.
- Contains malware, exploit code, or attempts to inject instructions into our AI systems.
- Contains other people's personal data beyond ordinary references (for example a referee's name and contact detail supplied with their knowledge).

Gradr has no public feed, public profile or public comment surface, so there is no community content area. If we add one, this section will be extended before it launches.

## 4. Prohibited technical activity

You must not:

- Bypass authentication, plan limits, credit metering, rate limits or paywalls.
- Scrape, crawl, bulk-export or systematically extract Gradr data, job listings or AI output.
- Reverse engineer the Service or probe it for vulnerabilities without written permission.
- Use the Service to build, benchmark or train a competing product or model.
- Interfere with the Service, other accounts, or the infrastructure it runs on.

Responsible security research is welcome — see [Security](/security) for how to report a vulnerability.

## 5. Sensitive data

Do not upload special-category data (health, biometric, racial or ethnic origin, political opinions, religious beliefs, sexual orientation, trade-union membership) or government identity documents. Gradr is not designed to process them, and doing so breaches this policy.

## 6. Recording other people

AI mock interviews may use your microphone, and your camera if you enable it. Do not use these features to capture any other identifiable person, and do not use Gradr to record a real interview with a real employer without that employer's consent.

## 7. Automated and AI use

You may connect Gradr to an assistant through our published integrations. You must not use automation to generate mass applications, to spam employers, or to submit content you have not reviewed. You remain accountable for anything sent under your name.

## 8. Enforcement

Where we reasonably believe this policy has been breached we may, proportionately to the breach: warn you, throttle or suspend a feature, suspend or terminate the account, remove offending content, or report unlawful activity to the authorities. Where the breach is minor and fixable, we will normally contact you first. Suspension for breach does not automatically create a refund entitlement — see the [Refund & Cancellation Policy](/refund-policy).

## 9. Reporting abuse and appeals

Report abuse or a policy breach to ${SELLER_CONTACT_EMAIL}. If your account is restricted and you believe we got it wrong, reply to the notice we send and we will review the decision with a human.
`;

export const AI_DISCLOSURE_V1 = `## 1. Gradr is an AI-assisted product

Most of what Gradr produces is generated by artificial intelligence: resume analysis and ATS scoring, job-to-resume match explanations, tailored application drafts and cover letters, mock interview questions and follow-ups, interview scorecards and transcripts, skill-gap analysis and career plans, and role or company summaries.

This page explains what that means in practice. It supplements the [Terms & Conditions](/terms) and the [Privacy Notice](/privacy).

## 2. What AI does in each feature

- **Resume analysis** — the document you upload is parsed into text, scored against deterministic checks, and then passed to a language model that writes the narrative feedback and rewrite suggestions.
- **Job matching** — your resume content and a job description are compared, and the model explains which requirements you meet, partly meet or miss. Match percentages are heuristics, not employer decisions.
- **Application materials** — resume rewrites and cover letters are drafted by a model from your own resume and the target role. They are drafts.
- **Mock interviews** — questions, spoken responses and follow-ups are generated. Your spoken answers are transcribed and scored to produce a feedback report.
- **Career guidance** — skill gaps and plans are computed from your scores and matches, then explained by a model.

## 3. AI output can be wrong

Generated output can be incomplete, out of date, internally inconsistent, or simply incorrect, including where it sounds confident. Scores, ATS ratings, match percentages, salary references and readiness signals are estimates produced by our own models and heuristics. They do not tell you how any specific employer, recruiter or applicant tracking system will actually treat your application.

**You must read, verify and edit anything Gradr generates before you send it to an employer.** You are responsible for the accuracy of every claim in the materials you submit — including anything a model wrote for you.

## 4. What we do not claim

- We do not guarantee interviews, offers, employment, salary outcomes or visa outcomes.
- We do not guarantee that a resume will pass any applicant tracking system.
- We do not provide legal, immigration, financial, medical or professional counselling advice.
- We do not represent employers, and simulated interviewers are not recruiters.

## 5. Third-party AI providers

Gradr does not train its own foundation models. Content you submit for an AI feature is sent to third-party model providers so they can return a result. Today those are reached through the Lovable AI gateway (Google Gemini models) for text generation and analysis, and speech providers for interview audio. The current list, and what each receives, is in the [sub-processor register](/subprocessors).

We do not sell your content, and we do not authorise these providers to use your content to train their foundation models. Providers process it to return the result and for their own abuse monitoring under their terms.

## 6. Human oversight and no automated decisions with legal effect

Gradr does not make hiring decisions, does not reject you from anything, and does not produce a decision that has a legal or similarly significant effect on you. Every output is advisory and is acted on by you. If you want a human to review something Gradr told you, email ${SELLER_CONTACT_EMAIL}.

## 7. Your inputs

Do not paste confidential employer material, other people's documents, or special-category data into AI features. See the [Acceptable Use Policy](/acceptable-use).

## 8. Questions

Ask us anything about how a specific feature uses AI: ${SELLER_CONTACT_EMAIL}.
`;

export const DISCLAIMER_V1 = `## 1. Informational purpose

Everything Gradr shows you — scores, feedback, job listings, salary references, interview reports, skill gaps, career plans and generated documents — is provided for general informational purposes to support your own decisions. It is not professional advice, and no adviser-client relationship is created by using ${SELLER_LEGAL_NAME}.

Gradr does not provide legal, immigration, tax, financial, medical or licensed career-counselling advice. Where a decision matters, consult a qualified professional in your jurisdiction.

## 2. No outcome guarantee

We do not promise that using Gradr will result in interviews, job offers, employment, a higher salary, or success with any applicant tracking system. Any statistics, examples or sample results shown in the product or on our marketing pages illustrate how a feature works; they are not a prediction of your result.

## 3. Third-party listings and employers

Job listings, company data and salary figures are sourced from third-party providers and public feeds. We do not verify, endorse or guarantee any listing, employer, recruiter or figure, and listings may be stale, duplicated or withdrawn. Any application, interview, contract or payment between you and an employer is strictly between you and them. Never pay a fee, share identity documents or share bank details with an employer you have not independently verified.

## 4. Availability

The Service is provided on an "as is" and "as available" basis. To the fullest extent permitted by law we exclude implied warranties of merchantability, fitness for a particular purpose, accuracy and non-infringement. We do not warrant uninterrupted or error-free operation, and we may perform maintenance or change features as described in the [Terms & Conditions](/terms).

## 5. Limitation of liability

To the fullest extent permitted by applicable law, ${SELLER_LEGAL_NAME} is not liable for:

- Loss of employment, job offers, income, opportunity, profits, goodwill or anticipated savings.
- Loss or corruption of data, save where caused by our failure to take reasonable technical measures.
- Decisions you take, or materials you submit to an employer, based on AI output you did not verify.
- Acts, omissions, listings or requests of employers, recruiters or other third parties.
- Indirect, incidental, special, consequential or punitive damages.

Where liability cannot lawfully be excluded, our total aggregate liability arising out of or relating to the Service is limited to the greater of the amount you paid us for the Service in the twelve months before the event giving rise to the claim, or USD 100.

## 6. What we never exclude

Nothing in this document limits liability for death or personal injury caused by negligence, for fraud or fraudulent misrepresentation, or for any other liability that cannot be excluded or limited under the law that applies to you. **If you are a consumer, you keep all mandatory statutory rights in your country of residence**, including any statutory rights of withdrawal or refund, and nothing here overrides them.

## 7. Interaction with the Terms

This page summarises and forms part of the disclaimer and liability provisions of the [Terms & Conditions](/terms). Where the Terms are more specific, the Terms apply. Questions: ${LEGAL_CONTACT_EMAIL}.
`;

export const AFFILIATE_DISCLOSURE_V1 = `## 1. Gradr runs an affiliate programme

Gradr operates a referral/affiliate programme. Approved partners receive a tracking link, and if someone signs up through that link and later pays for a plan, the partner earns a commission on that payment. The programme terms are on the [Affiliate Programme](/affiliates) page.

## 2. What this means if you clicked a partner link

- The partner is paid by us, not by you. **Your price is exactly the same** as it would be if you had come to ${SELLER_DOMAIN} directly.
- We store an attribution cookie (\`cf_ref\`) so the referring partner can be credited. It is in the optional "marketing & attribution" cookie category — if you decline that category, no attribution cookie is set. See the [Cookie Policy](/cookie-policy).
- A partner's opinion is their own. Reviews, comparisons, rankings and claims published by a partner are not written, approved or verified by us, and a commercial relationship exists that may influence them.
- Discounts a partner advertises are valid only if the code resolves in our checkout.

## 3. What this means if you are a partner

If you promote Gradr, you must disclose the commercial relationship clearly and conspicuously wherever you place a link, in the way your jurisdiction requires (for example the US FTC endorsement guides, the UK CAP Code, or EU unfair-commercial-practices rules). You must not:

- Claim to be Gradr, or imply official endorsement beyond "affiliate partner".
- Invent results, testimonials, statistics or outcome guarantees.
- Bid on Gradr brand terms in paid search, spam, or use cookie stuffing.
- Promote Gradr through unsolicited email or messaging.

Commissions on payments that are refunded, charged back or fraudulently generated are reversed. Breach of these rules ends participation and forfeits unpaid commission.

## 4. Our own content

Where Gradr's own pages recommend a third-party tool or service, we tell you if we earn anything from it. If a page carries no disclosure, we earn nothing from the recommendation.

## 5. Contact

Questions about the programme or a specific partner's claim: ${SELLER_CONTACT_EMAIL}.
`;

export const SUBPROCESSORS_V1 = `## 1. About this register

This page lists the third-party services that process personal data on Gradr's behalf so the product can work. It supports the [Privacy Notice](/privacy) and the [Data Processing Addendum](/dpa). We update it when a provider is added or replaced.

A service appears here only if it can receive personal data. Providers are used under their own terms and data-protection commitments; we do not authorise any of them to sell your data or to train foundation models on it.

## 2. Core platform

- **Lovable Cloud / Supabase** — the application database, authentication, file storage (resumes, interview reports) and server-side functions. Receives: account identifiers, all product data you create, uploaded files.
- **Lovable** — application hosting, the AI gateway and the transactional email pipeline. Receives: request metadata, AI prompts, email content and recipient address.

## 3. AI and voice

- **Lovable AI gateway → Google (Gemini models)** — resume analysis, job matching, generated applications, interview questions and feedback, career plans. Receives: the resume text, job description, or interview transcript relevant to the request.
- **ElevenLabs** — interview speech synthesis and, where enabled, speech-to-text. Receives: interview audio and/or the text to speak.
- **Fish Audio** — alternative speech provider for interview voice. Receives: interview audio and/or the text to speak.
- **Perplexity** — company and role research where that feature is used. Receives: the company or role query.

## 4. Payments

- **Paddle** — merchant of record: checkout, payment processing, subscription management, invoicing, sales tax/VAT. Receives: name, email, billing country, payment details (card data is handled by Paddle, never by Gradr).
- **RevenueCat** — subscription state reconciliation where mobile/store purchases apply. Receives: pseudonymous account identifier and subscription state.

## 5. Communications

- **Lovable email delivery (Resend infrastructure)** — transactional email: verification, password reset, billing notices, product notifications. Receives: email address, name, message content.

## 6. Analytics and diagnostics

- **PostHog (EU region by default)** — product analytics. Receives: pseudonymous user id and product events. Only loaded after you accept the analytics cookie category.
- **Sentry** — error and performance diagnostics. Receives: error traces, which may incidentally include the signed-in account id.
- **Google Search Console** — aggregate search performance for our public pages. Receives no visitor-level personal data.

## 7. Job data and enrichment

These providers supply listings and company information into Gradr. They receive search parameters (such as keywords and location), not your resume.

- **Adzuna** — job listing feed
- **Apify** — job listing collection
- **Corvi Careers** — job listing feed
- **JobMaps** — job listing feed
- **Logo.dev** — company logo lookup by domain

## 8. Identity providers and optional connections

Used only if you choose them:

- **Google, Apple, Microsoft** — sign-in. We receive the identifier, email and name they release; they learn that you signed in to Gradr.
- **Google Calendar** — only if you connect it, to write or read your interview events.

## 9. International transfers

Some providers process data outside your country, including in the United States. Where personal data covered by UK or EU/EEA law is transferred, we rely on the provider's transfer mechanism, normally the EU Standard Contractual Clauses and the UK Addendum, together with encryption in transit.

## 10. Questions or objections

Business customers with a signed [DPA](/dpa) can ask to be notified of changes to this register, and may object to a new sub-processor on reasonable data-protection grounds. Contact ${PRIVACY_CONTACT_EMAIL}.
`;

/** Short, plain-language notice reused at checkout and in billing surfaces. */
export const CHECKOUT_LEGAL_SUMMARY = [
  "Subscriptions renew automatically at the listed price and interval until you cancel.",
  "Cancel any time from Billing — you keep access until the end of the period you have paid for.",
  `Refunds are handled under our ${REFUND_WINDOW_DAYS}-day Refund & Cancellation Policy and your statutory rights.`,
  "Paddle is the merchant of record and shows any applicable sales tax or VAT before you pay.",
] as const;
