import { cn } from "@/lib/utils";

/**
 * Official Gradr symbol — the "aperture G": a squircle ring with an off-centre
 * counter, a machined aperture through the right stroke, and a crossbar capped
 * by the mahogany module.
 *
 * Generated by `scripts/generate-brand-logo.mjs` into public/, so the same
 * source backs the favicon, apple-touch icon, PWA icons and social cards.
 * The teal mark is used on light surfaces and the soft-white mark on dark ones;
 * both render and swap with CSS (`dark:`) so the right one paints on frame one.
 */
/**
 * UI marks use a 256px variant (~10KB instead of the 512px master) — the
 * full-size files stay reserved for PWA icons and social cards.
 */
export const BRAND_LOGO_URL = "/gradr-logo-256.png";
export const BRAND_LOGO_DARK_URL = "/gradr-logo-dark-256.png";
export const BRAND_LOGO_FULL_URL = "/gradr-logo.png";
/** Single-colour vector mark; inherits `color` via currentColor. */
export const BRAND_LOGO_MONO_URL = "/gradr-logo-mono.svg";
/** Symbol + GRADR wordmark, for docs, decks and email headers. */
export const BRAND_LOCKUP_URL = "/gradr-lockup.png";
export const BRAND_LOCKUP_DARK_URL = "/gradr-lockup-dark.png";


type BrandLogoProps = {
  /** Rendered box size in px. The source is square, so width === height. */
  size?: number;
  className?: string;
  /** Set false when the logo sits next to a visible "Gradr" wordmark. */
  decorative?: boolean;
  /** Above-the-fold marks (header, auth hero) should not lazy-load. */
  priority?: boolean;
};

export function BrandLogo({ size = 32, className, decorative = true, priority = true }: BrandLogoProps) {
  const shared = {
    width: size,
    height: size,
    style: { width: size, height: size },
    alt: decorative ? "" : "Gradr",
    "aria-hidden": decorative || undefined,
    draggable: false,
    decoding: "async" as const,
    loading: (priority ? "eager" : "lazy") as "eager" | "lazy",
  };

  return (
    <span
      className={cn("relative inline-grid shrink-0 place-items-center align-middle", className)}
      style={{ width: size, height: size }}
      data-brand-logo=""
    >
      <img
        {...shared}
        src={BRAND_LOGO_URL}
        className="col-start-1 row-start-1 block rounded-[22%] object-contain dark:hidden"
      />
      <img
        {...shared}
        src={BRAND_LOGO_DARK_URL}
        alt=""
        aria-hidden
        className="col-start-1 row-start-1 hidden rounded-[22%] object-contain dark:block"
      />
    </span>
  );
}
