/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AiInterviewCoachRouteImport } from './routes/ai-interview-coach'
import { Route as AtsResumeCheckerRouteImport } from './routes/ats-resume-checker'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppApplyRouteImport } from './routes/_app/apply'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppGrowthRouteImport } from './routes/_app/growth'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppManageSubscriptionRouteImport } from './routes/_app/manage-subscription'
import { Route as AppMatchRouteImport } from './routes/_app/match'
import { Route as AppMotionPlaygroundRouteImport } from './routes/_app/motion-playground'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppResumeRouteImport } from './routes/_app/resume'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogAiResumeOptimizationRouteImport } from './routes/blog/ai-resume-optimization'
import { Route as CareerAdviceIndexRouteImport } from './routes/career-advice/index'
import { Route as CareerAdviceSlugRouteImport } from './routes/career-advice/$slug'
import { Route as JobSearchIndexRouteImport } from './routes/job-search/index'
import { Route as JobSearchSlugRouteImport } from './routes/job-search/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppAdminAffiliatesRouteImport } from './routes/_app/admin/affiliates'
import { Route as AppAdminApiHealthRouteImport } from './routes/_app/admin/api-health'
import { Route as AppAdminAuditLogRouteImport } from './routes/_app/admin/audit-log'
import { Route as AppAdminBlogAnalyticsRouteImport } from './routes/_app/admin/blog-analytics'
import { Route as AppAdminDigestPreviewRouteImport } from './routes/_app/admin/digest-preview'
import { Route as AppAdminDiscountsRouteImport } from './routes/_app/admin/discounts'
import { Route as AppAdminLegalRouteImport } from './routes/_app/admin/legal'
import { Route as AppAdminNavAnalyticsRouteImport } from './routes/_app/admin/nav-analytics'
import { Route as AppAdminPaddleRouteImport } from './routes/_app/admin/paddle'
import { Route as AppAdminPaymentsStatusRouteImport } from './routes/_app/admin/payments-status'
import { Route as AppAdminSearchConsoleRouteImport } from './routes/_app/admin/search-console'
import { Route as AppAdminSecurityLogRouteImport } from './routes/_app/admin/security-log'
import { Route as AppAdminSeoMonitorRouteImport } from './routes/_app/admin/seo-monitor'
import { Route as AppAdminVerificationsRouteImport } from './routes/_app/admin/verifications'
import { Route as AppAffiliateIndexRouteImport } from './routes/_app/affiliate/index'
import { Route as AppAffiliateApplyRouteImport } from './routes/_app/affiliate/apply'
import { Route as AppAffiliateDashboardRouteImport } from './routes/_app/affiliate/dashboard'
import { Route as AppAffiliateResourcesRouteImport } from './routes/_app/affiliate/resources'
import { Route as AppInterviewIndexRouteImport } from './routes/_app/interview/index'
import { Route as AppInterviewHistoryRouteImport } from './routes/_app/interview/history'
import { Route as ApiPublicAdminRpcRouteImport } from './routes/api/public/admin-rpc'
import { Route as ApiPublicAdminWebhookReplayRouteImport } from './routes/api/public/admin-webhook-replay'
import { Route as ApiPublicAffiliatePublicRouteImport } from './routes/api/public/affiliate-public'
import { Route as ApiPublicAnalyzeResumeRouteImport } from './routes/api/public/analyze-resume'
import { Route as ApiPublicCalendarSyncRouteImport } from './routes/api/public/calendar-sync'
import { Route as ApiPublicCareerPlanRouteImport } from './routes/api/public/career-plan'
import { Route as ApiPublicCompanyResearchRouteImport } from './routes/api/public/company-research'
import { Route as ApiPublicDailyDigestRouteImport } from './routes/api/public/daily-digest'
import { Route as ApiPublicDeleteAccountRouteImport } from './routes/api/public/delete-account'
import { Route as ApiPublicGenerateApplicationRouteImport } from './routes/api/public/generate-application'
import { Route as ApiPublicGetPaddlePriceRouteImport } from './routes/api/public/get-paddle-price'
import { Route as ApiPublicInterviewCoachRouteImport } from './routes/api/public/interview-coach'
import { Route as ApiPublicInterviewRealtimeTokenRouteImport } from './routes/api/public/interview-realtime-token'
import { Route as ApiPublicInterviewReportRouteImport } from './routes/api/public/interview-report'
import { Route as ApiPublicInterviewVoiceRouteImport } from './routes/api/public/interview-voice'
import { Route as ApiPublicJobsApifyRouteImport } from './routes/api/public/jobs-apify'
import { Route as ApiPublicMatchJobsRouteImport } from './routes/api/public/match-jobs'
import { Route as ApiPublicNotifyPolicyUpdateRouteImport } from './routes/api/public/notify-policy-update'
import { Route as ApiPublicParseJobUrlRouteImport } from './routes/api/public/parse-job-url'
import { Route as ApiPublicPaymentsPortalRouteImport } from './routes/api/public/payments-portal'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments-webhook'
import { Route as ApiPublicPracticePlanRouteImport } from './routes/api/public/practice-plan'
import { Route as ApiPublicRecommendJobsRouteImport } from './routes/api/public/recommend-jobs'
import { Route as ApiPublicResolveDiscountRouteImport } from './routes/api/public/resolve-discount'
import { Route as ApiPublicRevenuecatSyncRouteImport } from './routes/api/public/revenuecat-sync'
import { Route as ApiPublicSearchConsoleRouteImport } from './routes/api/public/search-console'
import { Route as ApiPublicSearchJobsRouteImport } from './routes/api/public/search-jobs'
import { Route as ApiPublicSendNotificationRouteImport } from './routes/api/public/send-notification'
import { Route as ApiPublicSeoMonitorRouteImport } from './routes/api/public/seo-monitor'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInterviewCoachRoute = AiInterviewCoachRouteImport.update({
  id: '/ai-interview-coach',
  path: '/ai-interview-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsResumeCheckerRoute = AtsResumeCheckerRouteImport.update({
  id: '/ats-resume-checker',
  path: '/ats-resume-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyRoute = AppApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppManageSubscriptionRoute = AppManageSubscriptionRouteImport.update({
  id: '/manage-subscription',
  path: '/manage-subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppMotionPlaygroundRoute = AppMotionPlaygroundRouteImport.update({
  id: '/motion-playground',
  path: '/motion-playground',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAiResumeOptimizationRoute =
  BlogAiResumeOptimizationRouteImport.update({
    id: '/blog/ai-resume-optimization',
    path: '/blog/ai-resume-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerAdviceIndexRoute = CareerAdviceIndexRouteImport.update({
  id: '/career-advice/',
  path: '/career-advice/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAdviceSlugRoute = CareerAdviceSlugRouteImport.update({
  id: '/career-advice/$slug',
  path: '/career-advice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSearchIndexRoute = JobSearchIndexRouteImport.update({
  id: '/job-search/',
  path: '/job-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSearchSlugRoute = JobSearchSlugRouteImport.update({
  id: '/job-search/$slug',
  path: '/job-search/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAffiliatesRoute = AppAdminAffiliatesRouteImport.update({
  id: '/admin/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApiHealthRoute = AppAdminApiHealthRouteImport.update({
  id: '/admin/api-health',
  path: '/admin/api-health',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBlogAnalyticsRoute = AppAdminBlogAnalyticsRouteImport.update({
  id: '/admin/blog-analytics',
  path: '/admin/blog-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDigestPreviewRoute = AppAdminDigestPreviewRouteImport.update({
  id: '/admin/digest-preview',
  path: '/admin/digest-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDiscountsRoute = AppAdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLegalRoute = AppAdminLegalRouteImport.update({
  id: '/admin/legal',
  path: '/admin/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNavAnalyticsRoute = AppAdminNavAnalyticsRouteImport.update({
  id: '/admin/nav-analytics',
  path: '/admin/nav-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPaddleRoute = AppAdminPaddleRouteImport.update({
  id: '/admin/paddle',
  path: '/admin/paddle',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPaymentsStatusRoute = AppAdminPaymentsStatusRouteImport.update({
  id: '/admin/payments-status',
  path: '/admin/payments-status',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSearchConsoleRoute = AppAdminSearchConsoleRouteImport.update({
  id: '/admin/search-console',
  path: '/admin/search-console',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSecurityLogRoute = AppAdminSecurityLogRouteImport.update({
  id: '/admin/security-log',
  path: '/admin/security-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSeoMonitorRoute = AppAdminSeoMonitorRouteImport.update({
  id: '/admin/seo-monitor',
  path: '/admin/seo-monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminVerificationsRoute = AppAdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateIndexRoute = AppAffiliateIndexRouteImport.update({
  id: '/affiliate/',
  path: '/affiliate/',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateApplyRoute = AppAffiliateApplyRouteImport.update({
  id: '/affiliate/apply',
  path: '/affiliate/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateDashboardRoute = AppAffiliateDashboardRouteImport.update({
  id: '/affiliate/dashboard',
  path: '/affiliate/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateResourcesRoute = AppAffiliateResourcesRouteImport.update({
  id: '/affiliate/resources',
  path: '/affiliate/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewIndexRoute = AppInterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewHistoryRoute = AppInterviewHistoryRouteImport.update({
  id: '/interview/history',
  path: '/interview/history',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicAdminRpcRoute = ApiPublicAdminRpcRouteImport.update({
  id: '/api/public/admin-rpc',
  path: '/api/public/admin-rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminWebhookReplayRoute =
  ApiPublicAdminWebhookReplayRouteImport.update({
    id: '/api/public/admin-webhook-replay',
    path: '/api/public/admin-webhook-replay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAffiliatePublicRoute =
  ApiPublicAffiliatePublicRouteImport.update({
    id: '/api/public/affiliate-public',
    path: '/api/public/affiliate-public',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAnalyzeResumeRoute = ApiPublicAnalyzeResumeRouteImport.update({
  id: '/api/public/analyze-resume',
  path: '/api/public/analyze-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarSyncRoute = ApiPublicCalendarSyncRouteImport.update({
  id: '/api/public/calendar-sync',
  path: '/api/public/calendar-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCareerPlanRoute = ApiPublicCareerPlanRouteImport.update({
  id: '/api/public/career-plan',
  path: '/api/public/career-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompanyResearchRoute =
  ApiPublicCompanyResearchRouteImport.update({
    id: '/api/public/company-research',
    path: '/api/public/company-research',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDailyDigestRoute = ApiPublicDailyDigestRouteImport.update({
  id: '/api/public/daily-digest',
  path: '/api/public/daily-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeleteAccountRoute = ApiPublicDeleteAccountRouteImport.update({
  id: '/api/public/delete-account',
  path: '/api/public/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateApplicationRoute =
  ApiPublicGenerateApplicationRouteImport.update({
    id: '/api/public/generate-application',
    path: '/api/public/generate-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGetPaddlePriceRoute = ApiPublicGetPaddlePriceRouteImport.update({
  id: '/api/public/get-paddle-price',
  path: '/api/public/get-paddle-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInterviewCoachRoute = ApiPublicInterviewCoachRouteImport.update({
  id: '/api/public/interview-coach',
  path: '/api/public/interview-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInterviewRealtimeTokenRoute =
  ApiPublicInterviewRealtimeTokenRouteImport.update({
    id: '/api/public/interview-realtime-token',
    path: '/api/public/interview-realtime-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInterviewReportRoute =
  ApiPublicInterviewReportRouteImport.update({
    id: '/api/public/interview-report',
    path: '/api/public/interview-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInterviewVoiceRoute = ApiPublicInterviewVoiceRouteImport.update({
  id: '/api/public/interview-voice',
  path: '/api/public/interview-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsApifyRoute = ApiPublicJobsApifyRouteImport.update({
  id: '/api/public/jobs-apify',
  path: '/api/public/jobs-apify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMatchJobsRoute = ApiPublicMatchJobsRouteImport.update({
  id: '/api/public/match-jobs',
  path: '/api/public/match-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyPolicyUpdateRoute =
  ApiPublicNotifyPolicyUpdateRouteImport.update({
    id: '/api/public/notify-policy-update',
    path: '/api/public/notify-policy-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicParseJobUrlRoute = ApiPublicParseJobUrlRouteImport.update({
  id: '/api/public/parse-job-url',
  path: '/api/public/parse-job-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsPortalRoute = ApiPublicPaymentsPortalRouteImport.update({
  id: '/api/public/payments-portal',
  path: '/api/public/payments-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments-webhook',
    path: '/api/public/payments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPracticePlanRoute = ApiPublicPracticePlanRouteImport.update({
  id: '/api/public/practice-plan',
  path: '/api/public/practice-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecommendJobsRoute = ApiPublicRecommendJobsRouteImport.update({
  id: '/api/public/recommend-jobs',
  path: '/api/public/recommend-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResolveDiscountRoute =
  ApiPublicResolveDiscountRouteImport.update({
    id: '/api/public/resolve-discount',
    path: '/api/public/resolve-discount',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRevenuecatSyncRoute = ApiPublicRevenuecatSyncRouteImport.update({
  id: '/api/public/revenuecat-sync',
  path: '/api/public/revenuecat-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchConsoleRoute = ApiPublicSearchConsoleRouteImport.update({
  id: '/api/public/search-console',
  path: '/api/public/search-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchJobsRoute = ApiPublicSearchJobsRouteImport.update({
  id: '/api/public/search-jobs',
  path: '/api/public/search-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendNotificationRoute =
  ApiPublicSendNotificationRouteImport.update({
    id: '/api/public/send-notification',
    path: '/api/public/send-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSeoMonitorRoute = ApiPublicSeoMonitorRouteImport.update({
  id: '/api/public/seo-monitor',
  path: '/api/public/seo-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai-interview-coach': typeof AiInterviewCoachRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$': typeof AppSplatRoute
  '/apply': typeof AppApplyRoute
  '/billing': typeof AppBillingRoute
  '/growth': typeof AppGrowthRoute
  '/jobs': typeof AppJobsRoute
  '/manage-subscription': typeof AppManageSubscriptionRoute
  '/match': typeof AppMatchRoute
  '/motion-playground': typeof AppMotionPlaygroundRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pipeline': typeof AppPipelineRoute
  '/resume': typeof AppResumeRoute
  '/settings': typeof AppSettingsRoute
  '/welcome': typeof AppWelcomeRoute
  '/blog/ai-resume-optimization': typeof BlogAiResumeOptimizationRoute
  '/career-advice/$slug': typeof CareerAdviceSlugRoute
  '/job-search/$slug': typeof JobSearchSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/career-advice/': typeof CareerAdviceIndexRoute
  '/job-search/': typeof JobSearchIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/admin/api-health': typeof AppAdminApiHealthRoute
  '/admin/audit-log': typeof AppAdminAuditLogRoute
  '/admin/blog-analytics': typeof AppAdminBlogAnalyticsRoute
  '/admin/digest-preview': typeof AppAdminDigestPreviewRoute
  '/admin/discounts': typeof AppAdminDiscountsRoute
  '/admin/legal': typeof AppAdminLegalRoute
  '/admin/nav-analytics': typeof AppAdminNavAnalyticsRoute
  '/admin/paddle': typeof AppAdminPaddleRoute
  '/admin/payments-status': typeof AppAdminPaymentsStatusRoute
  '/admin/search-console': typeof AppAdminSearchConsoleRoute
  '/admin/security-log': typeof AppAdminSecurityLogRoute
  '/admin/seo-monitor': typeof AppAdminSeoMonitorRoute
  '/admin/verifications': typeof AppAdminVerificationsRoute
  '/affiliate/apply': typeof AppAffiliateApplyRoute
  '/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/affiliate/resources': typeof AppAffiliateResourcesRoute
  '/interview/history': typeof AppInterviewHistoryRoute
  '/api/public/admin-rpc': typeof ApiPublicAdminRpcRoute
  '/api/public/admin-webhook-replay': typeof ApiPublicAdminWebhookReplayRoute
  '/api/public/affiliate-public': typeof ApiPublicAffiliatePublicRoute
  '/api/public/analyze-resume': typeof ApiPublicAnalyzeResumeRoute
  '/api/public/calendar-sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/career-plan': typeof ApiPublicCareerPlanRoute
  '/api/public/company-research': typeof ApiPublicCompanyResearchRoute
  '/api/public/daily-digest': typeof ApiPublicDailyDigestRoute
  '/api/public/delete-account': typeof ApiPublicDeleteAccountRoute
  '/api/public/generate-application': typeof ApiPublicGenerateApplicationRoute
  '/api/public/get-paddle-price': typeof ApiPublicGetPaddlePriceRoute
  '/api/public/interview-coach': typeof ApiPublicInterviewCoachRoute
  '/api/public/interview-realtime-token': typeof ApiPublicInterviewRealtimeTokenRoute
  '/api/public/interview-report': typeof ApiPublicInterviewReportRoute
  '/api/public/interview-voice': typeof ApiPublicInterviewVoiceRoute
  '/api/public/jobs-apify': typeof ApiPublicJobsApifyRoute
  '/api/public/match-jobs': typeof ApiPublicMatchJobsRoute
  '/api/public/notify-policy-update': typeof ApiPublicNotifyPolicyUpdateRoute
  '/api/public/parse-job-url': typeof ApiPublicParseJobUrlRoute
  '/api/public/payments-portal': typeof ApiPublicPaymentsPortalRoute
  '/api/public/payments-webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/practice-plan': typeof ApiPublicPracticePlanRoute
  '/api/public/recommend-jobs': typeof ApiPublicRecommendJobsRoute
  '/api/public/resolve-discount': typeof ApiPublicResolveDiscountRoute
  '/api/public/revenuecat-sync': typeof ApiPublicRevenuecatSyncRoute
  '/api/public/search-console': typeof ApiPublicSearchConsoleRoute
  '/api/public/search-jobs': typeof ApiPublicSearchJobsRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/seo-monitor': typeof ApiPublicSeoMonitorRoute
  '/affiliate/': typeof AppAffiliateIndexRoute
  '/interview/': typeof AppInterviewIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/ai-interview-coach': typeof AiInterviewCoachRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$': typeof AppSplatRoute
  '/apply': typeof AppApplyRoute
  '/billing': typeof AppBillingRoute
  '/growth': typeof AppGrowthRoute
  '/jobs': typeof AppJobsRoute
  '/manage-subscription': typeof AppManageSubscriptionRoute
  '/match': typeof AppMatchRoute
  '/motion-playground': typeof AppMotionPlaygroundRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pipeline': typeof AppPipelineRoute
  '/resume': typeof AppResumeRoute
  '/settings': typeof AppSettingsRoute
  '/welcome': typeof AppWelcomeRoute
  '/blog/ai-resume-optimization': typeof BlogAiResumeOptimizationRoute
  '/career-advice/$slug': typeof CareerAdviceSlugRoute
  '/job-search/$slug': typeof JobSearchSlugRoute
  '/': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/career-advice': typeof CareerAdviceIndexRoute
  '/job-search': typeof JobSearchIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/admin/api-health': typeof AppAdminApiHealthRoute
  '/admin/audit-log': typeof AppAdminAuditLogRoute
  '/admin/blog-analytics': typeof AppAdminBlogAnalyticsRoute
  '/admin/digest-preview': typeof AppAdminDigestPreviewRoute
  '/admin/discounts': typeof AppAdminDiscountsRoute
  '/admin/legal': typeof AppAdminLegalRoute
  '/admin/nav-analytics': typeof AppAdminNavAnalyticsRoute
  '/admin/paddle': typeof AppAdminPaddleRoute
  '/admin/payments-status': typeof AppAdminPaymentsStatusRoute
  '/admin/search-console': typeof AppAdminSearchConsoleRoute
  '/admin/security-log': typeof AppAdminSecurityLogRoute
  '/admin/seo-monitor': typeof AppAdminSeoMonitorRoute
  '/admin/verifications': typeof AppAdminVerificationsRoute
  '/affiliate/apply': typeof AppAffiliateApplyRoute
  '/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/affiliate/resources': typeof AppAffiliateResourcesRoute
  '/interview/history': typeof AppInterviewHistoryRoute
  '/api/public/admin-rpc': typeof ApiPublicAdminRpcRoute
  '/api/public/admin-webhook-replay': typeof ApiPublicAdminWebhookReplayRoute
  '/api/public/affiliate-public': typeof ApiPublicAffiliatePublicRoute
  '/api/public/analyze-resume': typeof ApiPublicAnalyzeResumeRoute
  '/api/public/calendar-sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/career-plan': typeof ApiPublicCareerPlanRoute
  '/api/public/company-research': typeof ApiPublicCompanyResearchRoute
  '/api/public/daily-digest': typeof ApiPublicDailyDigestRoute
  '/api/public/delete-account': typeof ApiPublicDeleteAccountRoute
  '/api/public/generate-application': typeof ApiPublicGenerateApplicationRoute
  '/api/public/get-paddle-price': typeof ApiPublicGetPaddlePriceRoute
  '/api/public/interview-coach': typeof ApiPublicInterviewCoachRoute
  '/api/public/interview-realtime-token': typeof ApiPublicInterviewRealtimeTokenRoute
  '/api/public/interview-report': typeof ApiPublicInterviewReportRoute
  '/api/public/interview-voice': typeof ApiPublicInterviewVoiceRoute
  '/api/public/jobs-apify': typeof ApiPublicJobsApifyRoute
  '/api/public/match-jobs': typeof ApiPublicMatchJobsRoute
  '/api/public/notify-policy-update': typeof ApiPublicNotifyPolicyUpdateRoute
  '/api/public/parse-job-url': typeof ApiPublicParseJobUrlRoute
  '/api/public/payments-portal': typeof ApiPublicPaymentsPortalRoute
  '/api/public/payments-webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/practice-plan': typeof ApiPublicPracticePlanRoute
  '/api/public/recommend-jobs': typeof ApiPublicRecommendJobsRoute
  '/api/public/resolve-discount': typeof ApiPublicResolveDiscountRoute
  '/api/public/revenuecat-sync': typeof ApiPublicRevenuecatSyncRoute
  '/api/public/search-console': typeof ApiPublicSearchConsoleRoute
  '/api/public/search-jobs': typeof ApiPublicSearchJobsRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/seo-monitor': typeof ApiPublicSeoMonitorRoute
  '/affiliate': typeof AppAffiliateIndexRoute
  '/interview': typeof AppInterviewIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/ai-interview-coach': typeof AiInterviewCoachRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/apply': typeof AppApplyRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/growth': typeof AppGrowthRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/manage-subscription': typeof AppManageSubscriptionRoute
  '/_app/match': typeof AppMatchRoute
  '/_app/motion-playground': typeof AppMotionPlaygroundRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/resume': typeof AppResumeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/blog/ai-resume-optimization': typeof BlogAiResumeOptimizationRoute
  '/career-advice/$slug': typeof CareerAdviceSlugRoute
  '/job-search/$slug': typeof JobSearchSlugRoute
  '/_app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/career-advice/': typeof CareerAdviceIndexRoute
  '/job-search/': typeof JobSearchIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/_app/admin/api-health': typeof AppAdminApiHealthRoute
  '/_app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/_app/admin/blog-analytics': typeof AppAdminBlogAnalyticsRoute
  '/_app/admin/digest-preview': typeof AppAdminDigestPreviewRoute
  '/_app/admin/discounts': typeof AppAdminDiscountsRoute
  '/_app/admin/legal': typeof AppAdminLegalRoute
  '/_app/admin/nav-analytics': typeof AppAdminNavAnalyticsRoute
  '/_app/admin/paddle': typeof AppAdminPaddleRoute
  '/_app/admin/payments-status': typeof AppAdminPaymentsStatusRoute
  '/_app/admin/search-console': typeof AppAdminSearchConsoleRoute
  '/_app/admin/security-log': typeof AppAdminSecurityLogRoute
  '/_app/admin/seo-monitor': typeof AppAdminSeoMonitorRoute
  '/_app/admin/verifications': typeof AppAdminVerificationsRoute
  '/_app/affiliate/apply': typeof AppAffiliateApplyRoute
  '/_app/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/_app/affiliate/resources': typeof AppAffiliateResourcesRoute
  '/_app/interview/history': typeof AppInterviewHistoryRoute
  '/api/public/admin-rpc': typeof ApiPublicAdminRpcRoute
  '/api/public/admin-webhook-replay': typeof ApiPublicAdminWebhookReplayRoute
  '/api/public/affiliate-public': typeof ApiPublicAffiliatePublicRoute
  '/api/public/analyze-resume': typeof ApiPublicAnalyzeResumeRoute
  '/api/public/calendar-sync': typeof ApiPublicCalendarSyncRoute
  '/api/public/career-plan': typeof ApiPublicCareerPlanRoute
  '/api/public/company-research': typeof ApiPublicCompanyResearchRoute
  '/api/public/daily-digest': typeof ApiPublicDailyDigestRoute
  '/api/public/delete-account': typeof ApiPublicDeleteAccountRoute
  '/api/public/generate-application': typeof ApiPublicGenerateApplicationRoute
  '/api/public/get-paddle-price': typeof ApiPublicGetPaddlePriceRoute
  '/api/public/interview-coach': typeof ApiPublicInterviewCoachRoute
  '/api/public/interview-realtime-token': typeof ApiPublicInterviewRealtimeTokenRoute
  '/api/public/interview-report': typeof ApiPublicInterviewReportRoute
  '/api/public/interview-voice': typeof ApiPublicInterviewVoiceRoute
  '/api/public/jobs-apify': typeof ApiPublicJobsApifyRoute
  '/api/public/match-jobs': typeof ApiPublicMatchJobsRoute
  '/api/public/notify-policy-update': typeof ApiPublicNotifyPolicyUpdateRoute
  '/api/public/parse-job-url': typeof ApiPublicParseJobUrlRoute
  '/api/public/payments-portal': typeof ApiPublicPaymentsPortalRoute
  '/api/public/payments-webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/practice-plan': typeof ApiPublicPracticePlanRoute
  '/api/public/recommend-jobs': typeof ApiPublicRecommendJobsRoute
  '/api/public/resolve-discount': typeof ApiPublicResolveDiscountRoute
  '/api/public/revenuecat-sync': typeof ApiPublicRevenuecatSyncRoute
  '/api/public/search-console': typeof ApiPublicSearchConsoleRoute
  '/api/public/search-jobs': typeof ApiPublicSearchJobsRoute
  '/api/public/send-notification': typeof ApiPublicSendNotificationRoute
  '/api/public/seo-monitor': typeof ApiPublicSeoMonitorRoute
  '/_app/affiliate/': typeof AppAffiliateIndexRoute
  '/_app/interview/': typeof AppInterviewIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-interview-coach'
    | '/ats-resume-checker'
    | '/auth'
    | '/cookie-policy'
    | '/dpa'
    | '/forgot-password'
    | '/landing'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/$'
    | '/apply'
    | '/billing'
    | '/growth'
    | '/jobs'
    | '/manage-subscription'
    | '/match'
    | '/motion-playground'
    | '/onboarding'
    | '/pipeline'
    | '/resume'
    | '/settings'
    | '/welcome'
    | '/blog/ai-resume-optimization'
    | '/career-advice/$slug'
    | '/job-search/$slug'
    | '/blog/'
    | '/career-advice/'
    | '/job-search/'
    | '/.lovable/oauth/consent'
    | '/admin/affiliates'
    | '/admin/api-health'
    | '/admin/audit-log'
    | '/admin/blog-analytics'
    | '/admin/digest-preview'
    | '/admin/discounts'
    | '/admin/legal'
    | '/admin/nav-analytics'
    | '/admin/paddle'
    | '/admin/payments-status'
    | '/admin/search-console'
    | '/admin/security-log'
    | '/admin/seo-monitor'
    | '/admin/verifications'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/resources'
    | '/interview/history'
    | '/api/public/admin-rpc'
    | '/api/public/admin-webhook-replay'
    | '/api/public/affiliate-public'
    | '/api/public/analyze-resume'
    | '/api/public/calendar-sync'
    | '/api/public/career-plan'
    | '/api/public/company-research'
    | '/api/public/daily-digest'
    | '/api/public/delete-account'
    | '/api/public/generate-application'
    | '/api/public/get-paddle-price'
    | '/api/public/interview-coach'
    | '/api/public/interview-realtime-token'
    | '/api/public/interview-report'
    | '/api/public/interview-voice'
    | '/api/public/jobs-apify'
    | '/api/public/match-jobs'
    | '/api/public/notify-policy-update'
    | '/api/public/parse-job-url'
    | '/api/public/payments-portal'
    | '/api/public/payments-webhook'
    | '/api/public/practice-plan'
    | '/api/public/recommend-jobs'
    | '/api/public/resolve-discount'
    | '/api/public/revenuecat-sync'
    | '/api/public/search-console'
    | '/api/public/search-jobs'
    | '/api/public/send-notification'
    | '/api/public/seo-monitor'
    | '/affiliate/'
    | '/interview/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-interview-coach'
    | '/ats-resume-checker'
    | '/auth'
    | '/cookie-policy'
    | '/dpa'
    | '/forgot-password'
    | '/landing'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/$'
    | '/apply'
    | '/billing'
    | '/growth'
    | '/jobs'
    | '/manage-subscription'
    | '/match'
    | '/motion-playground'
    | '/onboarding'
    | '/pipeline'
    | '/resume'
    | '/settings'
    | '/welcome'
    | '/blog/ai-resume-optimization'
    | '/career-advice/$slug'
    | '/job-search/$slug'
    | '/'
    | '/blog'
    | '/career-advice'
    | '/job-search'
    | '/.lovable/oauth/consent'
    | '/admin/affiliates'
    | '/admin/api-health'
    | '/admin/audit-log'
    | '/admin/blog-analytics'
    | '/admin/digest-preview'
    | '/admin/discounts'
    | '/admin/legal'
    | '/admin/nav-analytics'
    | '/admin/paddle'
    | '/admin/payments-status'
    | '/admin/search-console'
    | '/admin/security-log'
    | '/admin/seo-monitor'
    | '/admin/verifications'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/resources'
    | '/interview/history'
    | '/api/public/admin-rpc'
    | '/api/public/admin-webhook-replay'
    | '/api/public/affiliate-public'
    | '/api/public/analyze-resume'
    | '/api/public/calendar-sync'
    | '/api/public/career-plan'
    | '/api/public/company-research'
    | '/api/public/daily-digest'
    | '/api/public/delete-account'
    | '/api/public/generate-application'
    | '/api/public/get-paddle-price'
    | '/api/public/interview-coach'
    | '/api/public/interview-realtime-token'
    | '/api/public/interview-report'
    | '/api/public/interview-voice'
    | '/api/public/jobs-apify'
    | '/api/public/match-jobs'
    | '/api/public/notify-policy-update'
    | '/api/public/parse-job-url'
    | '/api/public/payments-portal'
    | '/api/public/payments-webhook'
    | '/api/public/practice-plan'
    | '/api/public/recommend-jobs'
    | '/api/public/resolve-discount'
    | '/api/public/revenuecat-sync'
    | '/api/public/search-console'
    | '/api/public/search-jobs'
    | '/api/public/send-notification'
    | '/api/public/seo-monitor'
    | '/affiliate'
    | '/interview'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/_app'
    | '/ai-interview-coach'
    | '/ats-resume-checker'
    | '/auth'
    | '/cookie-policy'
    | '/dpa'
    | '/forgot-password'
    | '/landing'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/_app/$'
    | '/_app/apply'
    | '/_app/billing'
    | '/_app/growth'
    | '/_app/jobs'
    | '/_app/manage-subscription'
    | '/_app/match'
    | '/_app/motion-playground'
    | '/_app/onboarding'
    | '/_app/pipeline'
    | '/_app/resume'
    | '/_app/settings'
    | '/_app/welcome'
    | '/blog/ai-resume-optimization'
    | '/career-advice/$slug'
    | '/job-search/$slug'
    | '/_app/'
    | '/blog/'
    | '/career-advice/'
    | '/job-search/'
    | '/.lovable/oauth/consent'
    | '/_app/admin/affiliates'
    | '/_app/admin/api-health'
    | '/_app/admin/audit-log'
    | '/_app/admin/blog-analytics'
    | '/_app/admin/digest-preview'
    | '/_app/admin/discounts'
    | '/_app/admin/legal'
    | '/_app/admin/nav-analytics'
    | '/_app/admin/paddle'
    | '/_app/admin/payments-status'
    | '/_app/admin/search-console'
    | '/_app/admin/security-log'
    | '/_app/admin/seo-monitor'
    | '/_app/admin/verifications'
    | '/_app/affiliate/apply'
    | '/_app/affiliate/dashboard'
    | '/_app/affiliate/resources'
    | '/_app/interview/history'
    | '/api/public/admin-rpc'
    | '/api/public/admin-webhook-replay'
    | '/api/public/affiliate-public'
    | '/api/public/analyze-resume'
    | '/api/public/calendar-sync'
    | '/api/public/career-plan'
    | '/api/public/company-research'
    | '/api/public/daily-digest'
    | '/api/public/delete-account'
    | '/api/public/generate-application'
    | '/api/public/get-paddle-price'
    | '/api/public/interview-coach'
    | '/api/public/interview-realtime-token'
    | '/api/public/interview-report'
    | '/api/public/interview-voice'
    | '/api/public/jobs-apify'
    | '/api/public/match-jobs'
    | '/api/public/notify-policy-update'
    | '/api/public/parse-job-url'
    | '/api/public/payments-portal'
    | '/api/public/payments-webhook'
    | '/api/public/practice-plan'
    | '/api/public/recommend-jobs'
    | '/api/public/resolve-discount'
    | '/api/public/revenuecat-sync'
    | '/api/public/search-console'
    | '/api/public/search-jobs'
    | '/api/public/send-notification'
    | '/api/public/seo-monitor'
    | '/_app/affiliate/'
    | '/_app/interview/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AiInterviewCoachRoute: typeof AiInterviewCoachRoute
  AtsResumeCheckerRoute: typeof AtsResumeCheckerRoute
  AuthRoute: typeof AuthRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DpaRoute: typeof DpaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  BlogAiResumeOptimizationRoute: typeof BlogAiResumeOptimizationRoute
  CareerAdviceSlugRoute: typeof CareerAdviceSlugRoute
  JobSearchSlugRoute: typeof JobSearchSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CareerAdviceIndexRoute: typeof CareerAdviceIndexRoute
  JobSearchIndexRoute: typeof JobSearchIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicAdminRpcRoute: typeof ApiPublicAdminRpcRoute
  ApiPublicAdminWebhookReplayRoute: typeof ApiPublicAdminWebhookReplayRoute
  ApiPublicAffiliatePublicRoute: typeof ApiPublicAffiliatePublicRoute
  ApiPublicAnalyzeResumeRoute: typeof ApiPublicAnalyzeResumeRoute
  ApiPublicCalendarSyncRoute: typeof ApiPublicCalendarSyncRoute
  ApiPublicCareerPlanRoute: typeof ApiPublicCareerPlanRoute
  ApiPublicCompanyResearchRoute: typeof ApiPublicCompanyResearchRoute
  ApiPublicDailyDigestRoute: typeof ApiPublicDailyDigestRoute
  ApiPublicDeleteAccountRoute: typeof ApiPublicDeleteAccountRoute
  ApiPublicGenerateApplicationRoute: typeof ApiPublicGenerateApplicationRoute
  ApiPublicGetPaddlePriceRoute: typeof ApiPublicGetPaddlePriceRoute
  ApiPublicInterviewCoachRoute: typeof ApiPublicInterviewCoachRoute
  ApiPublicInterviewRealtimeTokenRoute: typeof ApiPublicInterviewRealtimeTokenRoute
  ApiPublicInterviewReportRoute: typeof ApiPublicInterviewReportRoute
  ApiPublicInterviewVoiceRoute: typeof ApiPublicInterviewVoiceRoute
  ApiPublicJobsApifyRoute: typeof ApiPublicJobsApifyRoute
  ApiPublicMatchJobsRoute: typeof ApiPublicMatchJobsRoute
  ApiPublicNotifyPolicyUpdateRoute: typeof ApiPublicNotifyPolicyUpdateRoute
  ApiPublicParseJobUrlRoute: typeof ApiPublicParseJobUrlRoute
  ApiPublicPaymentsPortalRoute: typeof ApiPublicPaymentsPortalRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPracticePlanRoute: typeof ApiPublicPracticePlanRoute
  ApiPublicRecommendJobsRoute: typeof ApiPublicRecommendJobsRoute
  ApiPublicResolveDiscountRoute: typeof ApiPublicResolveDiscountRoute
  ApiPublicRevenuecatSyncRoute: typeof ApiPublicRevenuecatSyncRoute
  ApiPublicSearchConsoleRoute: typeof ApiPublicSearchConsoleRoute
  ApiPublicSearchJobsRoute: typeof ApiPublicSearchJobsRoute
  ApiPublicSendNotificationRoute: typeof ApiPublicSendNotificationRoute
  ApiPublicSeoMonitorRoute: typeof ApiPublicSeoMonitorRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-interview-coach': {
      id: '/ai-interview-coach'
      path: '/ai-interview-coach'
      fullPath: '/ai-interview-coach'
      preLoaderRoute: typeof AiInterviewCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-resume-checker': {
      id: '/ats-resume-checker'
      path: '/ats-resume-checker'
      fullPath: '/ats-resume-checker'
      preLoaderRoute: typeof AtsResumeCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply': {
      id: '/_app/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AppApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth': {
      id: '/_app/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage-subscription': {
      id: '/_app/manage-subscription'
      path: '/manage-subscription'
      fullPath: '/manage-subscription'
      preLoaderRoute: typeof AppManageSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motion-playground': {
      id: '/_app/motion-playground'
      path: '/motion-playground'
      fullPath: '/motion-playground'
      preLoaderRoute: typeof AppMotionPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ai-resume-optimization': {
      id: '/blog/ai-resume-optimization'
      path: '/blog/ai-resume-optimization'
      fullPath: '/blog/ai-resume-optimization'
      preLoaderRoute: typeof BlogAiResumeOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advice/': {
      id: '/career-advice/'
      path: '/career-advice'
      fullPath: '/career-advice/'
      preLoaderRoute: typeof CareerAdviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advice/$slug': {
      id: '/career-advice/$slug'
      path: '/career-advice/$slug'
      fullPath: '/career-advice/$slug'
      preLoaderRoute: typeof CareerAdviceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search/': {
      id: '/job-search/'
      path: '/job-search'
      fullPath: '/job-search/'
      preLoaderRoute: typeof JobSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search/$slug': {
      id: '/job-search/$slug'
      path: '/job-search/$slug'
      fullPath: '/job-search/$slug'
      preLoaderRoute: typeof JobSearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/affiliates': {
      id: '/_app/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AppAdminAffiliatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/api-health': {
      id: '/_app/admin/api-health'
      path: '/admin/api-health'
      fullPath: '/admin/api-health'
      preLoaderRoute: typeof AppAdminApiHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit-log': {
      id: '/_app/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/blog-analytics': {
      id: '/_app/admin/blog-analytics'
      path: '/admin/blog-analytics'
      fullPath: '/admin/blog-analytics'
      preLoaderRoute: typeof AppAdminBlogAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/digest-preview': {
      id: '/_app/admin/digest-preview'
      path: '/admin/digest-preview'
      fullPath: '/admin/digest-preview'
      preLoaderRoute: typeof AppAdminDigestPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/discounts': {
      id: '/_app/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AppAdminDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/legal': {
      id: '/_app/admin/legal'
      path: '/admin/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AppAdminLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/nav-analytics': {
      id: '/_app/admin/nav-analytics'
      path: '/admin/nav-analytics'
      fullPath: '/admin/nav-analytics'
      preLoaderRoute: typeof AppAdminNavAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/paddle': {
      id: '/_app/admin/paddle'
      path: '/admin/paddle'
      fullPath: '/admin/paddle'
      preLoaderRoute: typeof AppAdminPaddleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/payments-status': {
      id: '/_app/admin/payments-status'
      path: '/admin/payments-status'
      fullPath: '/admin/payments-status'
      preLoaderRoute: typeof AppAdminPaymentsStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/search-console': {
      id: '/_app/admin/search-console'
      path: '/admin/search-console'
      fullPath: '/admin/search-console'
      preLoaderRoute: typeof AppAdminSearchConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/security-log': {
      id: '/_app/admin/security-log'
      path: '/admin/security-log'
      fullPath: '/admin/security-log'
      preLoaderRoute: typeof AppAdminSecurityLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/seo-monitor': {
      id: '/_app/admin/seo-monitor'
      path: '/admin/seo-monitor'
      fullPath: '/admin/seo-monitor'
      preLoaderRoute: typeof AppAdminSeoMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/verifications': {
      id: '/_app/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AppAdminVerificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/': {
      id: '/_app/affiliate/'
      path: '/affiliate'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AppAffiliateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/apply': {
      id: '/_app/affiliate/apply'
      path: '/affiliate/apply'
      fullPath: '/affiliate/apply'
      preLoaderRoute: typeof AppAffiliateApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/dashboard': {
      id: '/_app/affiliate/dashboard'
      path: '/affiliate/dashboard'
      fullPath: '/affiliate/dashboard'
      preLoaderRoute: typeof AppAffiliateDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/resources': {
      id: '/_app/affiliate/resources'
      path: '/affiliate/resources'
      fullPath: '/affiliate/resources'
      preLoaderRoute: typeof AppAffiliateResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/': {
      id: '/_app/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof AppInterviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/history': {
      id: '/_app/interview/history'
      path: '/interview/history'
      fullPath: '/interview/history'
      preLoaderRoute: typeof AppInterviewHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/admin-rpc': {
      id: '/api/public/admin-rpc'
      path: '/api/public/admin-rpc'
      fullPath: '/api/public/admin-rpc'
      preLoaderRoute: typeof ApiPublicAdminRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-webhook-replay': {
      id: '/api/public/admin-webhook-replay'
      path: '/api/public/admin-webhook-replay'
      fullPath: '/api/public/admin-webhook-replay'
      preLoaderRoute: typeof ApiPublicAdminWebhookReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affiliate-public': {
      id: '/api/public/affiliate-public'
      path: '/api/public/affiliate-public'
      fullPath: '/api/public/affiliate-public'
      preLoaderRoute: typeof ApiPublicAffiliatePublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-resume': {
      id: '/api/public/analyze-resume'
      path: '/api/public/analyze-resume'
      fullPath: '/api/public/analyze-resume'
      preLoaderRoute: typeof ApiPublicAnalyzeResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar-sync': {
      id: '/api/public/calendar-sync'
      path: '/api/public/calendar-sync'
      fullPath: '/api/public/calendar-sync'
      preLoaderRoute: typeof ApiPublicCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/career-plan': {
      id: '/api/public/career-plan'
      path: '/api/public/career-plan'
      fullPath: '/api/public/career-plan'
      preLoaderRoute: typeof ApiPublicCareerPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/company-research': {
      id: '/api/public/company-research'
      path: '/api/public/company-research'
      fullPath: '/api/public/company-research'
      preLoaderRoute: typeof ApiPublicCompanyResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-digest': {
      id: '/api/public/daily-digest'
      path: '/api/public/daily-digest'
      fullPath: '/api/public/daily-digest'
      preLoaderRoute: typeof ApiPublicDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delete-account': {
      id: '/api/public/delete-account'
      path: '/api/public/delete-account'
      fullPath: '/api/public/delete-account'
      preLoaderRoute: typeof ApiPublicDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-application': {
      id: '/api/public/generate-application'
      path: '/api/public/generate-application'
      fullPath: '/api/public/generate-application'
      preLoaderRoute: typeof ApiPublicGenerateApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-paddle-price': {
      id: '/api/public/get-paddle-price'
      path: '/api/public/get-paddle-price'
      fullPath: '/api/public/get-paddle-price'
      preLoaderRoute: typeof ApiPublicGetPaddlePriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-coach': {
      id: '/api/public/interview-coach'
      path: '/api/public/interview-coach'
      fullPath: '/api/public/interview-coach'
      preLoaderRoute: typeof ApiPublicInterviewCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-realtime-token': {
      id: '/api/public/interview-realtime-token'
      path: '/api/public/interview-realtime-token'
      fullPath: '/api/public/interview-realtime-token'
      preLoaderRoute: typeof ApiPublicInterviewRealtimeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-report': {
      id: '/api/public/interview-report'
      path: '/api/public/interview-report'
      fullPath: '/api/public/interview-report'
      preLoaderRoute: typeof ApiPublicInterviewReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interview-voice': {
      id: '/api/public/interview-voice'
      path: '/api/public/interview-voice'
      fullPath: '/api/public/interview-voice'
      preLoaderRoute: typeof ApiPublicInterviewVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs-apify': {
      id: '/api/public/jobs-apify'
      path: '/api/public/jobs-apify'
      fullPath: '/api/public/jobs-apify'
      preLoaderRoute: typeof ApiPublicJobsApifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/match-jobs': {
      id: '/api/public/match-jobs'
      path: '/api/public/match-jobs'
      fullPath: '/api/public/match-jobs'
      preLoaderRoute: typeof ApiPublicMatchJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-policy-update': {
      id: '/api/public/notify-policy-update'
      path: '/api/public/notify-policy-update'
      fullPath: '/api/public/notify-policy-update'
      preLoaderRoute: typeof ApiPublicNotifyPolicyUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/parse-job-url': {
      id: '/api/public/parse-job-url'
      path: '/api/public/parse-job-url'
      fullPath: '/api/public/parse-job-url'
      preLoaderRoute: typeof ApiPublicParseJobUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments-portal': {
      id: '/api/public/payments-portal'
      path: '/api/public/payments-portal'
      fullPath: '/api/public/payments-portal'
      preLoaderRoute: typeof ApiPublicPaymentsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments-webhook': {
      id: '/api/public/payments-webhook'
      path: '/api/public/payments-webhook'
      fullPath: '/api/public/payments-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/practice-plan': {
      id: '/api/public/practice-plan'
      path: '/api/public/practice-plan'
      fullPath: '/api/public/practice-plan'
      preLoaderRoute: typeof ApiPublicPracticePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recommend-jobs': {
      id: '/api/public/recommend-jobs'
      path: '/api/public/recommend-jobs'
      fullPath: '/api/public/recommend-jobs'
      preLoaderRoute: typeof ApiPublicRecommendJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resolve-discount': {
      id: '/api/public/resolve-discount'
      path: '/api/public/resolve-discount'
      fullPath: '/api/public/resolve-discount'
      preLoaderRoute: typeof ApiPublicResolveDiscountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/revenuecat-sync': {
      id: '/api/public/revenuecat-sync'
      path: '/api/public/revenuecat-sync'
      fullPath: '/api/public/revenuecat-sync'
      preLoaderRoute: typeof ApiPublicRevenuecatSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search-console': {
      id: '/api/public/search-console'
      path: '/api/public/search-console'
      fullPath: '/api/public/search-console'
      preLoaderRoute: typeof ApiPublicSearchConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search-jobs': {
      id: '/api/public/search-jobs'
      path: '/api/public/search-jobs'
      fullPath: '/api/public/search-jobs'
      preLoaderRoute: typeof ApiPublicSearchJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-notification': {
      id: '/api/public/send-notification'
      path: '/api/public/send-notification'
      fullPath: '/api/public/send-notification'
      preLoaderRoute: typeof ApiPublicSendNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seo-monitor': {
      id: '/api/public/seo-monitor'
      path: '/api/public/seo-monitor'
      fullPath: '/api/public/seo-monitor'
      preLoaderRoute: typeof ApiPublicSeoMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppApplyRoute: typeof AppApplyRoute
  AppBillingRoute: typeof AppBillingRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppJobsRoute: typeof AppJobsRoute
  AppManageSubscriptionRoute: typeof AppManageSubscriptionRoute
  AppMatchRoute: typeof AppMatchRoute
  AppMotionPlaygroundRoute: typeof AppMotionPlaygroundRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppResumeRoute: typeof AppResumeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAffiliatesRoute: typeof AppAdminAffiliatesRoute
  AppAdminApiHealthRoute: typeof AppAdminApiHealthRoute
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminBlogAnalyticsRoute: typeof AppAdminBlogAnalyticsRoute
  AppAdminDigestPreviewRoute: typeof AppAdminDigestPreviewRoute
  AppAdminDiscountsRoute: typeof AppAdminDiscountsRoute
  AppAdminLegalRoute: typeof AppAdminLegalRoute
  AppAdminNavAnalyticsRoute: typeof AppAdminNavAnalyticsRoute
  AppAdminPaddleRoute: typeof AppAdminPaddleRoute
  AppAdminPaymentsStatusRoute: typeof AppAdminPaymentsStatusRoute
  AppAdminSearchConsoleRoute: typeof AppAdminSearchConsoleRoute
  AppAdminSecurityLogRoute: typeof AppAdminSecurityLogRoute
  AppAdminSeoMonitorRoute: typeof AppAdminSeoMonitorRoute
  AppAdminVerificationsRoute: typeof AppAdminVerificationsRoute
  AppAffiliateApplyRoute: typeof AppAffiliateApplyRoute
  AppAffiliateDashboardRoute: typeof AppAffiliateDashboardRoute
  AppAffiliateResourcesRoute: typeof AppAffiliateResourcesRoute
  AppInterviewHistoryRoute: typeof AppInterviewHistoryRoute
  AppAffiliateIndexRoute: typeof AppAffiliateIndexRoute
  AppInterviewIndexRoute: typeof AppInterviewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppApplyRoute: AppApplyRoute,
  AppBillingRoute: AppBillingRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppJobsRoute: AppJobsRoute,
  AppManageSubscriptionRoute: AppManageSubscriptionRoute,
  AppMatchRoute: AppMatchRoute,
  AppMotionPlaygroundRoute: AppMotionPlaygroundRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppResumeRoute: AppResumeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAffiliatesRoute: AppAdminAffiliatesRoute,
  AppAdminApiHealthRoute: AppAdminApiHealthRoute,
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminBlogAnalyticsRoute: AppAdminBlogAnalyticsRoute,
  AppAdminDigestPreviewRoute: AppAdminDigestPreviewRoute,
  AppAdminDiscountsRoute: AppAdminDiscountsRoute,
  AppAdminLegalRoute: AppAdminLegalRoute,
  AppAdminNavAnalyticsRoute: AppAdminNavAnalyticsRoute,
  AppAdminPaddleRoute: AppAdminPaddleRoute,
  AppAdminPaymentsStatusRoute: AppAdminPaymentsStatusRoute,
  AppAdminSearchConsoleRoute: AppAdminSearchConsoleRoute,
  AppAdminSecurityLogRoute: AppAdminSecurityLogRoute,
  AppAdminSeoMonitorRoute: AppAdminSeoMonitorRoute,
  AppAdminVerificationsRoute: AppAdminVerificationsRoute,
  AppAffiliateApplyRoute: AppAffiliateApplyRoute,
  AppAffiliateDashboardRoute: AppAffiliateDashboardRoute,
  AppAffiliateResourcesRoute: AppAffiliateResourcesRoute,
  AppInterviewHistoryRoute: AppInterviewHistoryRoute,
  AppAffiliateIndexRoute: AppAffiliateIndexRoute,
  AppInterviewIndexRoute: AppInterviewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AiInterviewCoachRoute: AiInterviewCoachRoute,
  AtsResumeCheckerRoute: AtsResumeCheckerRoute,
  AuthRoute: AuthRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DpaRoute: DpaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  BlogAiResumeOptimizationRoute: BlogAiResumeOptimizationRoute,
  CareerAdviceSlugRoute: CareerAdviceSlugRoute,
  JobSearchSlugRoute: JobSearchSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CareerAdviceIndexRoute: CareerAdviceIndexRoute,
  JobSearchIndexRoute: JobSearchIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicAdminRpcRoute: ApiPublicAdminRpcRoute,
  ApiPublicAdminWebhookReplayRoute: ApiPublicAdminWebhookReplayRoute,
  ApiPublicAffiliatePublicRoute: ApiPublicAffiliatePublicRoute,
  ApiPublicAnalyzeResumeRoute: ApiPublicAnalyzeResumeRoute,
  ApiPublicCalendarSyncRoute: ApiPublicCalendarSyncRoute,
  ApiPublicCareerPlanRoute: ApiPublicCareerPlanRoute,
  ApiPublicCompanyResearchRoute: ApiPublicCompanyResearchRoute,
  ApiPublicDailyDigestRoute: ApiPublicDailyDigestRoute,
  ApiPublicDeleteAccountRoute: ApiPublicDeleteAccountRoute,
  ApiPublicGenerateApplicationRoute: ApiPublicGenerateApplicationRoute,
  ApiPublicGetPaddlePriceRoute: ApiPublicGetPaddlePriceRoute,
  ApiPublicInterviewCoachRoute: ApiPublicInterviewCoachRoute,
  ApiPublicInterviewRealtimeTokenRoute: ApiPublicInterviewRealtimeTokenRoute,
  ApiPublicInterviewReportRoute: ApiPublicInterviewReportRoute,
  ApiPublicInterviewVoiceRoute: ApiPublicInterviewVoiceRoute,
  ApiPublicJobsApifyRoute: ApiPublicJobsApifyRoute,
  ApiPublicMatchJobsRoute: ApiPublicMatchJobsRoute,
  ApiPublicNotifyPolicyUpdateRoute: ApiPublicNotifyPolicyUpdateRoute,
  ApiPublicParseJobUrlRoute: ApiPublicParseJobUrlRoute,
  ApiPublicPaymentsPortalRoute: ApiPublicPaymentsPortalRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPracticePlanRoute: ApiPublicPracticePlanRoute,
  ApiPublicRecommendJobsRoute: ApiPublicRecommendJobsRoute,
  ApiPublicResolveDiscountRoute: ApiPublicResolveDiscountRoute,
  ApiPublicRevenuecatSyncRoute: ApiPublicRevenuecatSyncRoute,
  ApiPublicSearchConsoleRoute: ApiPublicSearchConsoleRoute,
  ApiPublicSearchJobsRoute: ApiPublicSearchJobsRoute,
  ApiPublicSendNotificationRoute: ApiPublicSendNotificationRoute,
  ApiPublicSeoMonitorRoute: ApiPublicSeoMonitorRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
