/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AtsResumeCheckerRouteImport } from './routes/ats-resume-checker'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppApplyRouteImport } from './routes/_app/apply'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppGrowthRouteImport } from './routes/_app/growth'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppManageSubscriptionRouteImport } from './routes/_app/manage-subscription'
import { Route as AppMatchRouteImport } from './routes/_app/match'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppResumeRouteImport } from './routes/_app/resume'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWelcomeRouteImport } from './routes/_app/welcome'
import { Route as BlogAiResumeOptimizationRouteImport } from './routes/blog/ai-resume-optimization'
import { Route as CareerAdviceIndexRouteImport } from './routes/career-advice/index'
import { Route as CareerAdviceSlugRouteImport } from './routes/career-advice/$slug'
import { Route as JobSearchIndexRouteImport } from './routes/job-search/index'
import { Route as JobSearchSlugRouteImport } from './routes/job-search/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppAdminAffiliatesRouteImport } from './routes/_app/admin/affiliates'
import { Route as AppAdminAuditLogRouteImport } from './routes/_app/admin/audit-log'
import { Route as AppAdminBlogAnalyticsRouteImport } from './routes/_app/admin/blog-analytics'
import { Route as AppAdminDigestPreviewRouteImport } from './routes/_app/admin/digest-preview'
import { Route as AppAdminDiscountsRouteImport } from './routes/_app/admin/discounts'
import { Route as AppAdminLegalRouteImport } from './routes/_app/admin/legal'
import { Route as AppAdminNavAnalyticsRouteImport } from './routes/_app/admin/nav-analytics'
import { Route as AppAdminPaddleRouteImport } from './routes/_app/admin/paddle'
import { Route as AppAdminPaymentsStatusRouteImport } from './routes/_app/admin/payments-status'
import { Route as AppAdminSearchConsoleRouteImport } from './routes/_app/admin/search-console'
import { Route as AppAdminSecurityLogRouteImport } from './routes/_app/admin/security-log'
import { Route as AppAdminSeoMonitorRouteImport } from './routes/_app/admin/seo-monitor'
import { Route as AppAdminVerificationsRouteImport } from './routes/_app/admin/verifications'
import { Route as AppAffiliateIndexRouteImport } from './routes/_app/affiliate/index'
import { Route as AppAffiliateApplyRouteImport } from './routes/_app/affiliate/apply'
import { Route as AppAffiliateDashboardRouteImport } from './routes/_app/affiliate/dashboard'
import { Route as AppAffiliateResourcesRouteImport } from './routes/_app/affiliate/resources'
import { Route as AppInterviewIndexRouteImport } from './routes/_app/interview/index'
import { Route as AppInterviewHistoryRouteImport } from './routes/_app/interview/history'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsResumeCheckerRoute = AtsResumeCheckerRouteImport.update({
  id: '/ats-resume-checker',
  path: '/ats-resume-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyRoute = AppApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppGrowthRoute = AppGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppManageSubscriptionRoute = AppManageSubscriptionRouteImport.update({
  id: '/manage-subscription',
  path: '/manage-subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const BlogAiResumeOptimizationRoute =
  BlogAiResumeOptimizationRouteImport.update({
    id: '/blog/ai-resume-optimization',
    path: '/blog/ai-resume-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerAdviceIndexRoute = CareerAdviceIndexRouteImport.update({
  id: '/career-advice/',
  path: '/career-advice/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerAdviceSlugRoute = CareerAdviceSlugRouteImport.update({
  id: '/career-advice/$slug',
  path: '/career-advice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSearchIndexRoute = JobSearchIndexRouteImport.update({
  id: '/job-search/',
  path: '/job-search/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSearchSlugRoute = JobSearchSlugRouteImport.update({
  id: '/job-search/$slug',
  path: '/job-search/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAffiliatesRoute = AppAdminAffiliatesRouteImport.update({
  id: '/admin/affiliates',
  path: '/admin/affiliates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogRoute = AppAdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBlogAnalyticsRoute = AppAdminBlogAnalyticsRouteImport.update({
  id: '/admin/blog-analytics',
  path: '/admin/blog-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDigestPreviewRoute = AppAdminDigestPreviewRouteImport.update({
  id: '/admin/digest-preview',
  path: '/admin/digest-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDiscountsRoute = AppAdminDiscountsRouteImport.update({
  id: '/admin/discounts',
  path: '/admin/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLegalRoute = AppAdminLegalRouteImport.update({
  id: '/admin/legal',
  path: '/admin/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNavAnalyticsRoute = AppAdminNavAnalyticsRouteImport.update({
  id: '/admin/nav-analytics',
  path: '/admin/nav-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPaddleRoute = AppAdminPaddleRouteImport.update({
  id: '/admin/paddle',
  path: '/admin/paddle',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPaymentsStatusRoute = AppAdminPaymentsStatusRouteImport.update({
  id: '/admin/payments-status',
  path: '/admin/payments-status',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSearchConsoleRoute = AppAdminSearchConsoleRouteImport.update({
  id: '/admin/search-console',
  path: '/admin/search-console',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSecurityLogRoute = AppAdminSecurityLogRouteImport.update({
  id: '/admin/security-log',
  path: '/admin/security-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSeoMonitorRoute = AppAdminSeoMonitorRouteImport.update({
  id: '/admin/seo-monitor',
  path: '/admin/seo-monitor',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminVerificationsRoute = AppAdminVerificationsRouteImport.update({
  id: '/admin/verifications',
  path: '/admin/verifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateIndexRoute = AppAffiliateIndexRouteImport.update({
  id: '/affiliate/',
  path: '/affiliate/',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateApplyRoute = AppAffiliateApplyRouteImport.update({
  id: '/affiliate/apply',
  path: '/affiliate/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateDashboardRoute = AppAffiliateDashboardRouteImport.update({
  id: '/affiliate/dashboard',
  path: '/affiliate/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateResourcesRoute = AppAffiliateResourcesRouteImport.update({
  id: '/affiliate/resources',
  path: '/affiliate/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewIndexRoute = AppInterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewHistoryRoute = AppInterviewHistoryRouteImport.update({
  id: '/interview/history',
  path: '/interview/history',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$': typeof AppSplatRoute
  '/apply': typeof AppApplyRoute
  '/billing': typeof AppBillingRoute
  '/growth': typeof AppGrowthRoute
  '/jobs': typeof AppJobsRoute
  '/manage-subscription': typeof AppManageSubscriptionRoute
  '/match': typeof AppMatchRoute
  '/pipeline': typeof AppPipelineRoute
  '/resume': typeof AppResumeRoute
  '/settings': typeof AppSettingsRoute
  '/welcome': typeof AppWelcomeRoute
  '/blog/ai-resume-optimization': typeof BlogAiResumeOptimizationRoute
  '/career-advice/$slug': typeof CareerAdviceSlugRoute
  '/job-search/$slug': typeof JobSearchSlugRoute
  '/career-advice/': typeof CareerAdviceIndexRoute
  '/job-search/': typeof JobSearchIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/admin/audit-log': typeof AppAdminAuditLogRoute
  '/admin/blog-analytics': typeof AppAdminBlogAnalyticsRoute
  '/admin/digest-preview': typeof AppAdminDigestPreviewRoute
  '/admin/discounts': typeof AppAdminDiscountsRoute
  '/admin/legal': typeof AppAdminLegalRoute
  '/admin/nav-analytics': typeof AppAdminNavAnalyticsRoute
  '/admin/paddle': typeof AppAdminPaddleRoute
  '/admin/payments-status': typeof AppAdminPaymentsStatusRoute
  '/admin/search-console': typeof AppAdminSearchConsoleRoute
  '/admin/security-log': typeof AppAdminSecurityLogRoute
  '/admin/seo-monitor': typeof AppAdminSeoMonitorRoute
  '/admin/verifications': typeof AppAdminVerificationsRoute
  '/affiliate/apply': typeof AppAffiliateApplyRoute
  '/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/affiliate/resources': typeof AppAffiliateResourcesRoute
  '/interview/history': typeof AppInterviewHistoryRoute
  '/affiliate/': typeof AppAffiliateIndexRoute
  '/interview/': typeof AppInterviewIndexRoute
}
export interface FileRoutesByTo {
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$': typeof AppSplatRoute
  '/apply': typeof AppApplyRoute
  '/billing': typeof AppBillingRoute
  '/growth': typeof AppGrowthRoute
  '/jobs': typeof AppJobsRoute
  '/manage-subscription': typeof AppManageSubscriptionRoute
  '/match': typeof AppMatchRoute
  '/pipeline': typeof AppPipelineRoute
  '/resume': typeof AppResumeRoute
  '/settings': typeof AppSettingsRoute
  '/welcome': typeof AppWelcomeRoute
  '/blog/ai-resume-optimization': typeof BlogAiResumeOptimizationRoute
  '/career-advice/$slug': typeof CareerAdviceSlugRoute
  '/job-search/$slug': typeof JobSearchSlugRoute
  '/': typeof AppIndexRoute
  '/career-advice': typeof CareerAdviceIndexRoute
  '/job-search': typeof JobSearchIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/admin/audit-log': typeof AppAdminAuditLogRoute
  '/admin/blog-analytics': typeof AppAdminBlogAnalyticsRoute
  '/admin/digest-preview': typeof AppAdminDigestPreviewRoute
  '/admin/discounts': typeof AppAdminDiscountsRoute
  '/admin/legal': typeof AppAdminLegalRoute
  '/admin/nav-analytics': typeof AppAdminNavAnalyticsRoute
  '/admin/paddle': typeof AppAdminPaddleRoute
  '/admin/payments-status': typeof AppAdminPaymentsStatusRoute
  '/admin/search-console': typeof AppAdminSearchConsoleRoute
  '/admin/security-log': typeof AppAdminSecurityLogRoute
  '/admin/seo-monitor': typeof AppAdminSeoMonitorRoute
  '/admin/verifications': typeof AppAdminVerificationsRoute
  '/affiliate/apply': typeof AppAffiliateApplyRoute
  '/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/affiliate/resources': typeof AppAffiliateResourcesRoute
  '/interview/history': typeof AppInterviewHistoryRoute
  '/affiliate': typeof AppAffiliateIndexRoute
  '/interview': typeof AppInterviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/ats-resume-checker': typeof AtsResumeCheckerRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dpa': typeof DpaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/apply': typeof AppApplyRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/growth': typeof AppGrowthRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/manage-subscription': typeof AppManageSubscriptionRoute
  '/_app/match': typeof AppMatchRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/resume': typeof AppResumeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/blog/ai-resume-optimization': typeof BlogAiResumeOptimizationRoute
  '/career-advice/$slug': typeof CareerAdviceSlugRoute
  '/job-search/$slug': typeof JobSearchSlugRoute
  '/_app/': typeof AppIndexRoute
  '/career-advice/': typeof CareerAdviceIndexRoute
  '/job-search/': typeof JobSearchIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/_app/admin/audit-log': typeof AppAdminAuditLogRoute
  '/_app/admin/blog-analytics': typeof AppAdminBlogAnalyticsRoute
  '/_app/admin/digest-preview': typeof AppAdminDigestPreviewRoute
  '/_app/admin/discounts': typeof AppAdminDiscountsRoute
  '/_app/admin/legal': typeof AppAdminLegalRoute
  '/_app/admin/nav-analytics': typeof AppAdminNavAnalyticsRoute
  '/_app/admin/paddle': typeof AppAdminPaddleRoute
  '/_app/admin/payments-status': typeof AppAdminPaymentsStatusRoute
  '/_app/admin/search-console': typeof AppAdminSearchConsoleRoute
  '/_app/admin/security-log': typeof AppAdminSecurityLogRoute
  '/_app/admin/seo-monitor': typeof AppAdminSeoMonitorRoute
  '/_app/admin/verifications': typeof AppAdminVerificationsRoute
  '/_app/affiliate/apply': typeof AppAffiliateApplyRoute
  '/_app/affiliate/dashboard': typeof AppAffiliateDashboardRoute
  '/_app/affiliate/resources': typeof AppAffiliateResourcesRoute
  '/_app/interview/history': typeof AppInterviewHistoryRoute
  '/_app/affiliate/': typeof AppAffiliateIndexRoute
  '/_app/interview/': typeof AppInterviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats-resume-checker'
    | '/auth'
    | '/cookie-policy'
    | '/dpa'
    | '/forgot-password'
    | '/landing'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/$'
    | '/apply'
    | '/billing'
    | '/growth'
    | '/jobs'
    | '/manage-subscription'
    | '/match'
    | '/pipeline'
    | '/resume'
    | '/settings'
    | '/welcome'
    | '/blog/ai-resume-optimization'
    | '/career-advice/$slug'
    | '/job-search/$slug'
    | '/career-advice/'
    | '/job-search/'
    | '/.lovable/oauth/consent'
    | '/admin/affiliates'
    | '/admin/audit-log'
    | '/admin/blog-analytics'
    | '/admin/digest-preview'
    | '/admin/discounts'
    | '/admin/legal'
    | '/admin/nav-analytics'
    | '/admin/paddle'
    | '/admin/payments-status'
    | '/admin/search-console'
    | '/admin/security-log'
    | '/admin/seo-monitor'
    | '/admin/verifications'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/resources'
    | '/interview/history'
    | '/affiliate/'
    | '/interview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ats-resume-checker'
    | '/auth'
    | '/cookie-policy'
    | '/dpa'
    | '/forgot-password'
    | '/landing'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/$'
    | '/apply'
    | '/billing'
    | '/growth'
    | '/jobs'
    | '/manage-subscription'
    | '/match'
    | '/pipeline'
    | '/resume'
    | '/settings'
    | '/welcome'
    | '/blog/ai-resume-optimization'
    | '/career-advice/$slug'
    | '/job-search/$slug'
    | '/'
    | '/career-advice'
    | '/job-search'
    | '/.lovable/oauth/consent'
    | '/admin/affiliates'
    | '/admin/audit-log'
    | '/admin/blog-analytics'
    | '/admin/digest-preview'
    | '/admin/discounts'
    | '/admin/legal'
    | '/admin/nav-analytics'
    | '/admin/paddle'
    | '/admin/payments-status'
    | '/admin/search-console'
    | '/admin/security-log'
    | '/admin/seo-monitor'
    | '/admin/verifications'
    | '/affiliate/apply'
    | '/affiliate/dashboard'
    | '/affiliate/resources'
    | '/interview/history'
    | '/affiliate'
    | '/interview'
  id:
    | '__root__'
    | '/_app'
    | '/ats-resume-checker'
    | '/auth'
    | '/cookie-policy'
    | '/dpa'
    | '/forgot-password'
    | '/landing'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/_app/$'
    | '/_app/apply'
    | '/_app/billing'
    | '/_app/growth'
    | '/_app/jobs'
    | '/_app/manage-subscription'
    | '/_app/match'
    | '/_app/pipeline'
    | '/_app/resume'
    | '/_app/settings'
    | '/_app/welcome'
    | '/blog/ai-resume-optimization'
    | '/career-advice/$slug'
    | '/job-search/$slug'
    | '/_app/'
    | '/career-advice/'
    | '/job-search/'
    | '/.lovable/oauth/consent'
    | '/_app/admin/affiliates'
    | '/_app/admin/audit-log'
    | '/_app/admin/blog-analytics'
    | '/_app/admin/digest-preview'
    | '/_app/admin/discounts'
    | '/_app/admin/legal'
    | '/_app/admin/nav-analytics'
    | '/_app/admin/paddle'
    | '/_app/admin/payments-status'
    | '/_app/admin/search-console'
    | '/_app/admin/security-log'
    | '/_app/admin/seo-monitor'
    | '/_app/admin/verifications'
    | '/_app/affiliate/apply'
    | '/_app/affiliate/dashboard'
    | '/_app/affiliate/resources'
    | '/_app/interview/history'
    | '/_app/affiliate/'
    | '/_app/interview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AtsResumeCheckerRoute: typeof AtsResumeCheckerRoute
  AuthRoute: typeof AuthRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DpaRoute: typeof DpaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  BlogAiResumeOptimizationRoute: typeof BlogAiResumeOptimizationRoute
  CareerAdviceSlugRoute: typeof CareerAdviceSlugRoute
  JobSearchSlugRoute: typeof JobSearchSlugRoute
  CareerAdviceIndexRoute: typeof CareerAdviceIndexRoute
  JobSearchIndexRoute: typeof JobSearchIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-resume-checker': {
      id: '/ats-resume-checker'
      path: '/ats-resume-checker'
      fullPath: '/ats-resume-checker'
      preLoaderRoute: typeof AtsResumeCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply': {
      id: '/_app/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AppApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/growth': {
      id: '/_app/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AppGrowthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage-subscription': {
      id: '/_app/manage-subscription'
      path: '/manage-subscription'
      fullPath: '/manage-subscription'
      preLoaderRoute: typeof AppManageSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/ai-resume-optimization': {
      id: '/blog/ai-resume-optimization'
      path: '/blog/ai-resume-optimization'
      fullPath: '/blog/ai-resume-optimization'
      preLoaderRoute: typeof BlogAiResumeOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advice/': {
      id: '/career-advice/'
      path: '/career-advice'
      fullPath: '/career-advice/'
      preLoaderRoute: typeof CareerAdviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-advice/$slug': {
      id: '/career-advice/$slug'
      path: '/career-advice/$slug'
      fullPath: '/career-advice/$slug'
      preLoaderRoute: typeof CareerAdviceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search/': {
      id: '/job-search/'
      path: '/job-search'
      fullPath: '/job-search/'
      preLoaderRoute: typeof JobSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-search/$slug': {
      id: '/job-search/$slug'
      path: '/job-search/$slug'
      fullPath: '/job-search/$slug'
      preLoaderRoute: typeof JobSearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/affiliates': {
      id: '/_app/admin/affiliates'
      path: '/admin/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AppAdminAffiliatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit-log': {
      id: '/_app/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AppAdminAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/blog-analytics': {
      id: '/_app/admin/blog-analytics'
      path: '/admin/blog-analytics'
      fullPath: '/admin/blog-analytics'
      preLoaderRoute: typeof AppAdminBlogAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/digest-preview': {
      id: '/_app/admin/digest-preview'
      path: '/admin/digest-preview'
      fullPath: '/admin/digest-preview'
      preLoaderRoute: typeof AppAdminDigestPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/discounts': {
      id: '/_app/admin/discounts'
      path: '/admin/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AppAdminDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/legal': {
      id: '/_app/admin/legal'
      path: '/admin/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AppAdminLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/nav-analytics': {
      id: '/_app/admin/nav-analytics'
      path: '/admin/nav-analytics'
      fullPath: '/admin/nav-analytics'
      preLoaderRoute: typeof AppAdminNavAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/paddle': {
      id: '/_app/admin/paddle'
      path: '/admin/paddle'
      fullPath: '/admin/paddle'
      preLoaderRoute: typeof AppAdminPaddleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/payments-status': {
      id: '/_app/admin/payments-status'
      path: '/admin/payments-status'
      fullPath: '/admin/payments-status'
      preLoaderRoute: typeof AppAdminPaymentsStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/search-console': {
      id: '/_app/admin/search-console'
      path: '/admin/search-console'
      fullPath: '/admin/search-console'
      preLoaderRoute: typeof AppAdminSearchConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/security-log': {
      id: '/_app/admin/security-log'
      path: '/admin/security-log'
      fullPath: '/admin/security-log'
      preLoaderRoute: typeof AppAdminSecurityLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/seo-monitor': {
      id: '/_app/admin/seo-monitor'
      path: '/admin/seo-monitor'
      fullPath: '/admin/seo-monitor'
      preLoaderRoute: typeof AppAdminSeoMonitorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/verifications': {
      id: '/_app/admin/verifications'
      path: '/admin/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AppAdminVerificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/': {
      id: '/_app/affiliate/'
      path: '/affiliate'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AppAffiliateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/apply': {
      id: '/_app/affiliate/apply'
      path: '/affiliate/apply'
      fullPath: '/affiliate/apply'
      preLoaderRoute: typeof AppAffiliateApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/dashboard': {
      id: '/_app/affiliate/dashboard'
      path: '/affiliate/dashboard'
      fullPath: '/affiliate/dashboard'
      preLoaderRoute: typeof AppAffiliateDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate/resources': {
      id: '/_app/affiliate/resources'
      path: '/affiliate/resources'
      fullPath: '/affiliate/resources'
      preLoaderRoute: typeof AppAffiliateResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/': {
      id: '/_app/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof AppInterviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/history': {
      id: '/_app/interview/history'
      path: '/interview/history'
      fullPath: '/interview/history'
      preLoaderRoute: typeof AppInterviewHistoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppApplyRoute: typeof AppApplyRoute
  AppBillingRoute: typeof AppBillingRoute
  AppGrowthRoute: typeof AppGrowthRoute
  AppJobsRoute: typeof AppJobsRoute
  AppManageSubscriptionRoute: typeof AppManageSubscriptionRoute
  AppMatchRoute: typeof AppMatchRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppResumeRoute: typeof AppResumeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAffiliatesRoute: typeof AppAdminAffiliatesRoute
  AppAdminAuditLogRoute: typeof AppAdminAuditLogRoute
  AppAdminBlogAnalyticsRoute: typeof AppAdminBlogAnalyticsRoute
  AppAdminDigestPreviewRoute: typeof AppAdminDigestPreviewRoute
  AppAdminDiscountsRoute: typeof AppAdminDiscountsRoute
  AppAdminLegalRoute: typeof AppAdminLegalRoute
  AppAdminNavAnalyticsRoute: typeof AppAdminNavAnalyticsRoute
  AppAdminPaddleRoute: typeof AppAdminPaddleRoute
  AppAdminPaymentsStatusRoute: typeof AppAdminPaymentsStatusRoute
  AppAdminSearchConsoleRoute: typeof AppAdminSearchConsoleRoute
  AppAdminSecurityLogRoute: typeof AppAdminSecurityLogRoute
  AppAdminSeoMonitorRoute: typeof AppAdminSeoMonitorRoute
  AppAdminVerificationsRoute: typeof AppAdminVerificationsRoute
  AppAffiliateApplyRoute: typeof AppAffiliateApplyRoute
  AppAffiliateDashboardRoute: typeof AppAffiliateDashboardRoute
  AppAffiliateResourcesRoute: typeof AppAffiliateResourcesRoute
  AppInterviewHistoryRoute: typeof AppInterviewHistoryRoute
  AppAffiliateIndexRoute: typeof AppAffiliateIndexRoute
  AppInterviewIndexRoute: typeof AppInterviewIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppApplyRoute: AppApplyRoute,
  AppBillingRoute: AppBillingRoute,
  AppGrowthRoute: AppGrowthRoute,
  AppJobsRoute: AppJobsRoute,
  AppManageSubscriptionRoute: AppManageSubscriptionRoute,
  AppMatchRoute: AppMatchRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppResumeRoute: AppResumeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAffiliatesRoute: AppAdminAffiliatesRoute,
  AppAdminAuditLogRoute: AppAdminAuditLogRoute,
  AppAdminBlogAnalyticsRoute: AppAdminBlogAnalyticsRoute,
  AppAdminDigestPreviewRoute: AppAdminDigestPreviewRoute,
  AppAdminDiscountsRoute: AppAdminDiscountsRoute,
  AppAdminLegalRoute: AppAdminLegalRoute,
  AppAdminNavAnalyticsRoute: AppAdminNavAnalyticsRoute,
  AppAdminPaddleRoute: AppAdminPaddleRoute,
  AppAdminPaymentsStatusRoute: AppAdminPaymentsStatusRoute,
  AppAdminSearchConsoleRoute: AppAdminSearchConsoleRoute,
  AppAdminSecurityLogRoute: AppAdminSecurityLogRoute,
  AppAdminSeoMonitorRoute: AppAdminSeoMonitorRoute,
  AppAdminVerificationsRoute: AppAdminVerificationsRoute,
  AppAffiliateApplyRoute: AppAffiliateApplyRoute,
  AppAffiliateDashboardRoute: AppAffiliateDashboardRoute,
  AppAffiliateResourcesRoute: AppAffiliateResourcesRoute,
  AppInterviewHistoryRoute: AppInterviewHistoryRoute,
  AppAffiliateIndexRoute: AppAffiliateIndexRoute,
  AppInterviewIndexRoute: AppInterviewIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AtsResumeCheckerRoute: AtsResumeCheckerRoute,
  AuthRoute: AuthRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DpaRoute: DpaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  BlogAiResumeOptimizationRoute: BlogAiResumeOptimizationRoute,
  CareerAdviceSlugRoute: CareerAdviceSlugRoute,
  JobSearchSlugRoute: JobSearchSlugRoute,
  CareerAdviceIndexRoute: CareerAdviceIndexRoute,
  JobSearchIndexRoute: JobSearchIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
