// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-resumes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.24.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_resumes_default = defineTool({
  name: "list_resumes",
  title: "List resumes",
  description: "List the signed-in user's uploaded resumes with their ATS scores and AI analysis metadata.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum resumes to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("resumes").select("id, file_name, ats_score, keyword_match, formatting_score, impact_score, readability_score, created_at, updated_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { resumes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tracked-jobs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.24.2";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tracked_jobs_default = defineTool2({
  name: "list_tracked_jobs",
  title: "List tracked jobs",
  description: "List jobs the signed-in user is tracking in their Gradr pipeline, optionally filtered by status.",
  inputSchema: {
    status: z2.string().optional().describe("Filter by pipeline status (e.g. 'saved', 'applied', 'interview', 'offer', 'rejected')."),
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum jobs to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("tracked_jobs").select("id, title, company, location, status, match_score, salary_min, salary_max, remote, applied_at, created_at, notes").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-tracked-job.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.24.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_tracked_job_default = defineTool3({
  name: "create_tracked_job",
  title: "Add tracked job",
  description: "Add a job opportunity to the signed-in user's Gradr pipeline.",
  inputSchema: {
    title: z3.string().min(1).describe("Job title (e.g. 'Senior Frontend Engineer')."),
    company: z3.string().optional().describe("Company name."),
    location: z3.string().optional().describe("Job location."),
    status: z3.string().optional().describe("Initial pipeline status. Defaults to 'saved'."),
    remote: z3.boolean().optional().describe("Whether the role is remote."),
    salary_min: z3.number().optional(),
    salary_max: z3.number().optional(),
    description: z3.string().optional().describe("Full job description text."),
    notes: z3.string().optional(),
    source: z3.string().optional().describe("Where this job came from (e.g. 'linkedin', 'manual').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("tracked_jobs").insert({
      user_id: ctx.getUserId(),
      title: input.title,
      company: input.company ?? null,
      location: input.location ?? null,
      status: input.status ?? "saved",
      remote: input.remote ?? null,
      salary_min: input.salary_min ?? null,
      salary_max: input.salary_max ?? null,
      description: input.description ?? null,
      notes: input.notes ?? null,
      source: input.source ?? "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Added "${data.title}" to your pipeline.` }],
      structuredContent: { job: data }
    };
  }
});

// src/lib/mcp/tools/list-job-matches.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.24.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_job_matches_default = defineTool4({
  name: "list_job_matches",
  title: "List AI job matches",
  description: "List AI-generated job matches for the signed-in user, sorted by match score.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).optional().describe("Maximum matches to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("job_matches").select("*").order("match_score", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { matches: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.112.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool5({
  name: "get_profile",
  title: "Get my Gradr profile",
  description: "Return the signed-in user's Gradr profile: name, email, target role, and career preferences.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser5(ctx);
    const [profile, prefs] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle(),
      supabase.from("user_preferences").select("*").eq("user_id", ctx.getUserId()).maybeSingle()
    ]);
    if (profile.error) return { content: [{ type: "text", text: profile.error.message }], isError: true };
    const result = { profile: profile.data, preferences: prefs.data ?? null, email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xaeyjrekewnwjujnrqgu";
var mcp_default = defineMcp({
  name: "gradr-mcp",
  title: "Gradr",
  version: "0.1.0",
  instructions: "Tools for the signed-in Gradr user. Use `get_profile` for identity and career preferences, `list_resumes` and `list_job_matches` for AI resume + matching data, and `list_tracked_jobs` / `create_tracked_job` to read and write the user's job pipeline.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_resumes_default, list_job_matches_default, list_tracked_jobs_default, create_tracked_job_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
