// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeuiozgbtrzoiuhjasxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldWlvemdidHJ6b2l1aGphc3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5MTU4MDEsImV4cCI6MjEwMTQ5MTgwMX0.MsLbqpwWsWNumbtFlvlKoXrCZboCfhfjVXEfr1DXWzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});