// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { instrumentedFetch } from '@/lib/telemetry/supabaseErrorReporter';

const SUPABASE_URL = "https://xaeyjrekewnwjujnrqgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZXlqcmVrZXdud2p1am5ycWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3OTgyNDIsImV4cCI6MjA5MDM3NDI0Mn0.Tji8JPfXSSlFjPqvK10t0tK3_7IsgQddrHverZlLUqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: The generated `Database` types currently describe a different schema than
// the one this app targets, so the client is intentionally loosely typed until the
// target schema is mirrored and types are regenerated.
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: { fetch: instrumentedFetch },
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});